const char* tests[] = {
  "integer",
  "1",
  "integer",
  "character varying(32)",
  "1",
  "character varying(32)",
  "EXISTS(SELECT 1)",
  "2",
  "EXISTS(SELECT $1)",
  "v_version IS NULL",
  "2",
  "v_version IS NULL",
  "pos:= instr($1, $2, 1)",
  "3",
  "pos:= instr($1, $2, $3)",
  "temp_str := substring(string FROM beg_index)",
  "3",
  "temp_str := substring(string FROM beg_index)",
  "v3.c1 := 4",
  "4",
  "v3.c1 := $1",
  "NEW.name = upper(cleanString(NEW.name))",
  "4",
  "NEW.name = upper(cleanString(NEW.name))",
  "NEW.author.first_name = upper(cleanString(NEW.author.first_name))",
  "5",
  "NEW.author.first_name = upper(cleanString(NEW.author.first_name))",
  // PG_QUERY_PARSE_ALL
  "SELECT 1",
  "6",
  "SELECT $1",
  "integer",
  "6",
  "integer",
  "character varying(32)",
  "6",
  "character varying(32)",
  "EXISTS(SELECT 1)",
  "6",
  "EXISTS(SELECT $1)",
  "v_version IS NULL",
  "6",
  "v_version IS NULL",
  "pos:= instr($1, $2, 1)",
  "6",
  "pos:= instr($1, $2, $3)",
  "temp_str := substring(string FROM beg_index)",
  "6",
  "temp_str := substring(string FROM beg_index)",
  "v3.c1 := 4",
  "6",
  "v3.c1 := $1",
  "NEW.name = upper(cleanString(NEW.name))",
  "6",
  "NEW.name = upper(cleanString(NEW.name))",
  "NEW.author.first_name = upper(cleanString(NEW.author.first_name))",
  "6",
  "NEW.author.first_name = upper(cleanString(NEW.author.first_name))",
};

size_t testsLength = __LINE__ - 5;
