package LibpgQuery::NodeSupport::Outfuncs;

# Generates the node output/input support shared by the JSON and Protobuf
# output formats and the Protobuf input format, as well as the Protobuf
# definition itself:
#
#   pg_query_enum_defs.c       - _enumToString / _enumToInt / _intToEnum helpers
#   pg_query_outfuncs_defs.c   - _out<Node> functions (WRITE_*_FIELD macro calls)
#   pg_query_outfuncs_conds.c  - dispatch cases for _outNode
#   pg_query_readfuncs_defs.c  - _read<Node> functions (READ_*_FIELD macro calls)
#   pg_query_readfuncs_conds.c - dispatch cases for _readNode
#   pg_query.proto             - Protobuf definition
#
# The macros are defined by the including files (pg_query_outfuncs_json.c,
# pg_query_outfuncs_protobuf.c, pg_query_readfuncs_protobuf.c). Protobuf field
# numbers are assigned sequentially in field declaration order, so which fields
# are emitted (see outfuncs_skip_fields in overrides.pl) determines wire
# compatibility.

use strict;
use warnings FATAL => 'all';

use LibpgQuery::NodeSupport::Common
  qw(elem write_file node_fields parse_tree_nodes underscore);

my $HEADER =
  "// This file is autogenerated by ./scripts/generate_node_support.sh\n\n";

my @INT_TYPES = qw(int int16 int32 AttrNumber ParseLoc);
my @UINT_TYPES =
  qw(uint uint16 uint32 Index bits32 Oid SubTransactionId RelFileNumber);
my @UINT64_TYPES = qw(uint64 AclMode);
my @FLOAT_TYPES = qw(float double Cost Cardinality Selectivity);
my @BITMAPSET_TYPES = ('Bitmapset*', 'Relids');

# Value node types with hand-written support, appended to the Node oneof
my @VALUE_NODE_TYPES =
  qw(Integer Float Boolean String BitString List IntList OidList A_Const);

# Dispatch cases for the hand-written value node support
my $OUT_CONDS_PREAMBLE = <<'EOT';
case T_Integer:
  OUT_NODE(Integer, Integer, integer, INTEGER, Integer, integer);
  break;
case T_Boolean:
  OUT_NODE(Boolean, Boolean, boolean, BOOLEAN, Boolean, boolean);
  break;
case T_Float:
  OUT_NODE(Float, Float, float, FLOAT, Float, float_);
  break;
case T_String:
  OUT_NODE(String, String, string, STRING, String, string);
  break;
case T_BitString:
  OUT_NODE(BitString, BitString, bit_string, BIT_STRING, BitString, bit_string);
  break;
case T_List:
  OUT_NODE(List, List, list, LIST, List, list);
  break;
case T_IntList:
  OUT_NODE(IntList, IntList, int_list, INT_LIST, List, int_list);
  break;
case T_OidList:
  OUT_NODE(OidList, OidList, oid_list, OID_LIST, List, oid_list);
  break;
case T_A_Const:
  OUT_NODE(A_Const, AConst, a__const, A_CONST, A_Const, a_const);
  break;
EOT

my $PROTO_PREAMBLE = <<'EOT';
syntax = "proto3";

package pg_query;

message ParseResult {
  int32 version = 1;
  repeated RawStmt stmts = 2;
}

message ScanResult {
  int32 version = 1;
  repeated ScanToken tokens = 2;
}

message Node {
  oneof node {
EOT

my $PROTO_VALUE_MESSAGES = <<'EOT';
  }
}

message Integer
{
  int32 ival = 1; /* machine integer */
}

message Float
{
  string fval = 1; /* string */
}

message Boolean
{
  bool boolval = 1;
}

message String
{
  string sval = 1; /* string */
}

message BitString
{
  string bsval = 1; /* string */
}

message List
{
  repeated Node items = 1;
}

message OidList
{
  repeated Node items = 1;
}

message IntList
{
  repeated Node items = 1;
}

message A_Const
{
  oneof val {
    Integer ival = 1;
    Float fval = 2;
    Boolean boolval = 3;
    String sval = 4;
    BitString bsval = 5;
  }
  bool isnull = 10;
  int32 location = 11;
}

EOT

my $PROTO_SCAN = <<'EOT';


message ScanToken {
  int32 start = 1;
  int32 end = 2;
  Token token = 4;
  KeywordKind keyword_kind = 5;
}

enum KeywordKind {
  NO_KEYWORD = 0;
  UNRESERVED_KEYWORD = 1;
  COL_NAME_KEYWORD = 2;
  TYPE_FUNC_NAME_KEYWORD = 3;
  RESERVED_KEYWORD = 4;
}

enum Token {
  NUL = 0;
  // Single-character tokens that are returned 1:1 (identical with "self" list in scan.l)
  // Either supporting syntax, or single-character operators (some can be both)
  // Also see https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-SPECIAL-CHARS
  ASCII_36 = 36; // "$"
  ASCII_37 = 37; // "%"
  ASCII_40 = 40; // "("
  ASCII_41 = 41; // ")"
  ASCII_42 = 42; // "*"
  ASCII_43 = 43; // "+"
  ASCII_44 = 44; // ","
  ASCII_45 = 45; // "-"
  ASCII_46 = 46; // "."
  ASCII_47 = 47; // "/"
  ASCII_58 = 58; // ":"
  ASCII_59 = 59; // ";"
  ASCII_60 = 60; // "<"
  ASCII_61 = 61; // "="
  ASCII_62 = 62; // ">"
  ASCII_63 = 63; // "?"
  ASCII_91 = 91; // "["
  ASCII_92 = 92; // "\"
  ASCII_93 = 93; // "]"
  ASCII_94 = 94; // "^"
  // Named tokens in scan.l
EOT

my $PROTO_POSTAMBLE = <<'EOT';
}


// protobuf-c doesn't support optional fields, so any optional strings
// are just an empty string if it should be the equivalent of None/nil.
//
// These fields have `// optional` at the end of the line.
//
// Upstream issue: https://github.com/protobuf-c/protobuf-c/issues/476
message SummaryResult {
  enum Context {
    None = 0;
    Select = 1;
    DML = 2;
    DDL = 3;
    Call = 4;
  }

  message Table {
    string name = 1;
    string schema_name = 2;
    string table_name = 3;
    Context context = 4;
  }
  repeated Table tables = 1;

  // The value here is the table name (i.e. schema.table or just table).
  map<string, string> aliases = 2;

  repeated string cte_names = 3;

  message Function {
    string name = 1;
    string function_name = 2;
    string schema_name = 3; // optional
    Context context = 4;
  }
  repeated Function functions = 4;

  message FilterColumn {
    string schema_name = 1; // optional
    string table_name = 2; // optional
    string column = 3;
  }
  repeated FilterColumn filter_columns = 5;
  repeated string statement_types = 6;
  string truncated_query = 7; /* optional, empty if truncation limit is -1 */
}
EOT

sub generate
{
	my ($ctx, $ov, $enums) = @_;
	my @node_types = @{ $ctx->{node_types} };
	my @abstract_types = @{ $ctx->{abstract_types} };
	my @enum_types = @{ $ctx->{enum_types} };

	my %exclude = map { $_ => 1 } @{ $ov->{outfuncs_exclude_nodes} || [] };
	my %skip_fields = %{ $ov->{outfuncs_skip_fields} || {} };
	my %outname_overrides = %{ $ov->{outfuncs_outname_overrides} || {} };
	my %explicit_tag =
	  map { $_ => 1 } @{ $ov->{outfuncs_explicit_tag_nodes} || [] };

	my $out_defs = '';
	my $out_impls = '';
	my $out_conds = $OUT_CONDS_PREAMBLE;
	my $read_defs = '';
	my $read_impls = '';
	my $read_conds = '';
	my $proto_messages = '';
	my @proto_nodes;

	foreach my $n (parse_tree_nodes($ctx))
	{
		next if elem $n, @abstract_types;
		next if $exclude{$n};

		my $out = '';
		my $read = '';
		my $msg = '';
		my $field_no = 1;

		# typedef aliases (e.g. DistinctExpr for OpExpr) share the field
		# policy of the node type they alias
		my $policy_node = $ctx->{node_type_info}->{$n}->{alias_of} // $n;

		foreach my $fe (node_fields($ctx, $n))
		{
			my ($f, $t, $attrs) = @$fe;

			next if $skip_fields{"$policy_node.$f"};
			die
			  "$n.$f is marked read_write_ignore by Postgres, but not listed in outfuncs_skip_fields (add it to skip it, or decide to output it anyway)\n"
			  if elem 'read_write_ignore', @$attrs;

			my $o = $outname_overrides{"$policy_node.$f"} // underscore($f);
			my $j = $f;

			# Adds a field, optionally with out/read macro calls
			my $add = sub {
				my ($write_macro, $read_macro, $proto_type) = @_;
				$out .= "  $write_macro;\n" if defined $write_macro;
				$read .= "  $read_macro;\n" if defined $read_macro;
				$msg .=
				  "  $proto_type $o = $field_no [json_name=\"$j\"];\n";
				$field_no++;
			};
			my $simple = sub {
				my ($kind, $proto_type) = @_;
				$add->(
					"WRITE_${kind}_FIELD($o, $j, $f)",
					"READ_${kind}_FIELD($o, $j, $f)", $proto_type);
			};

			if ($t eq 'NodeTag')
			{
				# nothing to output
			}
			elsif ($t eq 'char')
			{
				$simple->('CHAR', 'string');
			}
			elsif ($t eq 'bool')
			{
				$simple->('BOOL', 'bool');
			}
			elsif ($t eq 'long')
			{
				$simple->('LONG', 'int64');
			}
			elsif (elem $t, @INT_TYPES)
			{
				$simple->('INT', 'int32');
			}
			elsif (elem $t, @UINT_TYPES)
			{
				$simple->('UINT', 'uint32');
			}
			elsif (elem $t, @UINT64_TYPES)
			{
				$simple->('UINT64', 'uint64');
			}
			elsif ($t eq 'char*')
			{
				$simple->('STRING', 'string');
			}
			elsif (elem $t, @FLOAT_TYPES)
			{
				$simple->('FLOAT', 'double');
			}
			elsif (elem $t, @BITMAPSET_TYPES)
			{
				$simple->('BITMAPSET', 'repeated uint64');
			}
			elsif ($t eq 'List*')
			{
				$simple->('LIST', 'repeated Node');
			}
			elsif ($t eq 'Node*')
			{
				$simple->('NODE_PTR', 'Node');
			}
			elsif ($t eq 'Node')
			{
				$simple->('NODE', 'Node');
			}
			elsif ($t =~ /^(\w+)\*$/ and elem $1, @abstract_types)
			{
				# pointer to an abstract node type, requires a cast when reading
				$add->(
					"WRITE_NODE_PTR_FIELD($o, $j, $f)",
					"READ_ABSTRACT_PTR_FIELD($o, $j, $f, $t)", 'Node');
			}
			elsif (elem $t, @abstract_types)
			{
				# embedded abstract node type (e.g. Expr xpr): consumes a
				# protobuf field number, but has nothing to output
				$add->(undef, undef, 'Node');
			}
			elsif ($t !~ /\*/ and elem $t, @node_types)
			{
				# embedded node struct (e.g. CreateForeignTableStmt.base)
				my $u = underscore($t);
				$add->(
					"WRITE_SPECIFIC_NODE_FIELD($t, $u, $o, $j, $f)",
					"READ_SPECIFIC_NODE_FIELD($t, $u, $o, $j, $f)", $t);
			}
			elsif ($t =~ /^(\w+)\*$/ and elem $1, @node_types)
			{
				my $nt = $1;
				my $u = underscore($nt);
				$add->(
					"WRITE_SPECIFIC_NODE_PTR_FIELD($nt, $u, $o, $j, $f)",
					"READ_SPECIFIC_NODE_PTR_FIELD($nt, $u, $o, $j, $f)", $nt);
			}
			elsif (elem $t, @enum_types)
			{
				$add->(
					"WRITE_ENUM_FIELD($t, $o, $j, $f)",
					"READ_ENUM_FIELD($t, $o, $j, $f)", $t);
			}
			else
			{
				die
				  "could not handle type \"$t\" in struct \"$n\" field \"$f\" for output (add it to outfuncs_skip_fields to skip it)\n";
			}
		}

		my $c = $n;
		$c =~ s/_//g;
		my $u = underscore($c);
		my $uu = uc $u;
		$uu =~ s/__/_/g;
		my $un = underscore($n);

		$out_defs .=
		  "static void _out$c(OUT_TYPE($n, $c) out_node, const $n *node);\n";
		$out_impls .= "static void\n";
		$out_impls .= "_out$c(OUT_TYPE($n, $c) out, const $n *node)\n";
		$out_impls .= "{\n$out}\n\n";
		$out_conds .= "case T_$n:\n";
		$out_conds .= "  OUT_NODE($n, $c, $u, $uu, $n, $un);\n";
		$out_conds .= "  break;\n";

		$read_defs .= "static $n * _read$c(OUT_TYPE($n, $c) msg);\n";
		$read_impls .= "static $n *\n";
		$read_impls .= "_read$c(OUT_TYPE($n, $c) msg)\n";
		$read_impls .= "{\n";
		$read_impls .= "  $n *node = makeNode($n);\n";
		$read_impls .= $read;
		$read_impls .= "  NodeSetTag(node, T_$n);\n" if $explicit_tag{$n};
		$read_impls .= "  return node;\n";
		$read_impls .= "}\n\n";
		$read_conds .= "  READ_COND($n, $c, $u, $uu, $n, $un);\n";

		$proto_messages .= "message $n\n{\n$msg}\n\n";
		push @proto_nodes,
		  sprintf('%s %s = %d [json_name="%s"];',
			$n, $un, scalar(@proto_nodes) + 1, $n);
	}

	foreach my $n (@VALUE_NODE_TYPES)
	{
		push @proto_nodes,
		  sprintf('%s %s = %d [json_name="%s"];',
			$n, underscore($n), scalar(@proto_nodes) + 1, $n);
	}

	# enums
	my @enum_to_strings;
	my @enum_to_ints;
	my @int_to_enums;
	my @proto_enums;

	foreach my $e (@{ $enums->{enums} })
	{
		my $name = $e->{name};
		my @members = @{ $e->{members} };

		# The dummy zero value is intentionally never used in practice, this
		# ensures the JSON output always includes the enum value (and doesn't
		# skip it because it is the zero value)
		my $pe = "enum $name\n{\n  " . uc(underscore($name)) . "_UNDEFINED = 0;\n";
		my $es =
		  "static const char*\n_enumToString$name($name value) {\n  switch(value) {\n";
		my $ei = "static int\n_enumToInt$name($name value) {\n  switch(value) {\n";
		my $ie = "static $name\n_intToEnum$name(int value) {\n  switch(value) {\n";

		my $i = 1;
		foreach my $v (@members)
		{
			$pe .= "  $v = $i;\n";
			$es .= "    case $v: return \"$v\";\n";
			$ei .= "    case $v: return $i;\n";
			$ie .= "    case $i: return $v;\n";
			$i++;
		}

		push @proto_enums, $pe . "}";
		push @enum_to_strings, $es . "  }\n  Assert(false);\n  return NULL;\n}";
		push @enum_to_ints, $ei . "  }\n  Assert(false);\n  return -1;\n}";
		push @int_to_enums,
		  $ie . "  }\n  Assert(false);\n  return $members[0];\n}";
	}

	$proto_messages .= join("\n\n", @proto_enums);

	my @scan_tokens = map { "$_->[0] = $_->[1];" } @{ $enums->{scan_tokens} };

	my $proto = $HEADER . $PROTO_PREAMBLE;
	$proto .= "\t\t" . join("\n    ", @proto_nodes) . "\n";
	$proto .= $PROTO_VALUE_MESSAGES;
	$proto .= $proto_messages;
	$proto .= $PROTO_SCAN;
	$proto .= "  " . join("\n  ", @scan_tokens) . "\n";
	$proto .= $PROTO_POSTAMBLE;

	my $outdir = $ctx->{outdir};
	write_file("$outdir/pg_query_enum_defs.c",
		$HEADER
		  . join("\n\n", @enum_to_strings)
		  . join("\n\n", @enum_to_ints)
		  . join("\n\n", @int_to_enums));
	write_file("$outdir/pg_query_outfuncs_defs.c",
		$HEADER . $out_defs . "\n\n" . $out_impls);
	write_file("$outdir/pg_query_outfuncs_conds.c", $HEADER . $out_conds);
	write_file("$outdir/pg_query_readfuncs_defs.c",
		$HEADER . $read_defs . "\n\n" . $read_impls);
	write_file("$outdir/pg_query_readfuncs_conds.c", $HEADER . $read_conds);
	write_file("$outdir/pg_query.proto", $proto);
	return;
}

1;
