package LibpgQuery::NodeSupport::Plpgsql;

# Generates the output support for PL/pgSQL parse trees (PLpgSQL_function and
# everything reachable from it), from gen_node_support.pl's parse of
# plpgsql.h, which is passed to it via --hook-extra-input since its structs
# are not nodes:
#
#   pg_query_outfuncs_plpgsql_defs.c - _outPLpgSQL_* functions (WRITE_*_FIELD
#                                      macro calls), the cmd_type / dtype
#                                      dispatchers, and the enum helpers for
#                                      the PL/pgSQL enums
#
# plus fragments that Outfuncs.pm and Srcdata.pm merge into pg_query.proto and
# srcdata/*.json. Like pg_query_outfuncs_defs.c, the generated C file is
# backend-agnostic: the macros are defined by the including files
# (pg_query_outfuncs_json.c, pg_query_outfuncs_protobuf.c,
# pg_query_outfuncs_protobuf_cpp.cc).
#
# All policy lives in the plpgsql section of overrides.pl. Every field of
# every reachable struct must be accounted for there (emitted, skipped, or
# consumed by an array/linked list/custom entry), and protobuf field numbers
# follow the order of the emit lists, so a field Postgres adds to plpgsql.h
# can neither silently leak into the output nor renumber existing fields.

use strict;
use warnings FATAL => 'all';

use LibpgQuery::NodeSupport::Common qw(elem write_file underscore scalar_kind);
use LibpgQuery::NodeSupport::Enums;
use LibpgQuery::NodeSupport::Outfuncs;

my $HEADER =
  "// This file is autogenerated by ./scripts/generate_node_support.sh\n\n";

# Top-level message wrapping the output of pg_query_parse_plpgsql_protobuf
my $RESULT_MESSAGE = <<'EOT';
message PLpgSQLParseResult
{
  int32 version = 1;
  repeated PLpgSQL_function functions = 2;
}
EOT

# Field name a struct gets as a oneof member of its dispatch wrapper
# (PLpgSQL_stmt_block => stmt_block, PLpgSQL_var => var)
sub oneof_field
{
	my ($struct) = @_;
	(my $f = $struct) =~ s/^PLpgSQL_//;
	return lc $f;
}

sub generate
{
	my ($ctx, $ov, $enums) = @_;

	my $pl = $ov->{plpgsql}
	  or die "overrides.pl has no plpgsql section\n";
	my $info = $ctx->{extra_struct_info};
	die "no extra struct info, was --hook-extra-input .../plpgsql.h passed to gen_node_support.pl?\n"
	  unless $info && %$info;

	my %enum_known = map { $_->{name} => 1 } @{ $enums->{enums} };

	# PL/pgSQL enums, with member values (needed for the oneof tags)
	my @header_enums = LibpgQuery::NodeSupport::Enums::parse_header(
		"$ctx->{srcdir}/$pl->{header}");
	my %enum_members;
	foreach my $e (@header_enums)
	{
		die "enum $e->{name} from $pl->{header} is unknown to gen_node_support.pl\n"
		  unless elem $e->{name}, @{ $ctx->{extra_enum_types} };
		$enum_members{ $e->{name} } = $e->{members};
	}

	# Resolve the dispatch (polymorphic pointer) wrappers to their concrete
	# structs: wrapper => [ { value_name, value, struct }, ... ] in enum order
	my %dispatch;
	foreach my $wrapper (sort keys %{ $pl->{dispatch} })
	{
		my $d = $pl->{dispatch}{$wrapper};
		die "dispatch wrapper $wrapper is not a struct in $pl->{header}\n"
		  unless $info->{$wrapper};
		die "dispatch wrapper $wrapper has no $d->{tag_field} field\n"
		  unless $info->{$wrapper}{field_types}{ $d->{tag_field} };
		my $members = $enum_members{ $d->{enum} }
		  or die "dispatch enum $d->{enum} not found in $pl->{header}\n";

		my @cases;
		foreach my $m (@$members)
		{
			my $struct = $d->{structs}{ $m->{name} };
			unless (defined $struct)
			{
				(my $suffix = $m->{name}) =~ s/^\Q$d->{value_prefix}\E//
				  or die "$d->{enum} value $m->{name} does not start with $d->{value_prefix}\n";
				$struct = $d->{struct_prefix} . lc($suffix);
			}
			die "$d->{enum} value $m->{name} maps to $struct, which is not a struct in $pl->{header} (add a dispatch.structs entry in overrides.pl if the naming convention does not apply)\n"
			  unless $info->{$struct};
			push @cases,
			  { value_name => $m->{name}, value => $m->{value}, struct => $struct };
		}
		$dispatch{$wrapper} = \@cases;
	}

	my %datum_type = map { $_ => 1 } @{ $pl->{datum_types} };

	# Element type of a List* field
	my $list_elem = sub {
		my ($s, $f) = @_;
		my $e = $pl->{list_elem_types}{"$s.$f"} // $pl->{list_elem_types}{$f}
		  or die "no list_elem_types entry for $s.$f in overrides.pl\n";
		die "list element type $e of $s.$f is not a struct in $pl->{header}\n"
		  unless $info->{$e};
		return $e;
	};

	# Fields consumed by array / linked list / custom entries, which thus
	# need no emit/skip classification of their own
	my %consumed;
	foreach my $k (keys %{ $pl->{arrays} })
	{
		my ($s) = split /\./, $k;
		$consumed{"$s.$pl->{arrays}{$k}"} = $k;
	}
	foreach my $k (keys %{ $pl->{linked_lists} })
	{
		my ($s, $f) = split /\./, $k;
		(my $e = $info->{$s}{field_types}{$f} // '') =~ s/^struct\s+//;
		$e =~ s/\*$// or die "linked list $k is not a pointer field\n";
		$consumed{"$e.$pl->{linked_lists}{$k}"} = $k;
	}
	foreach my $k (keys %{ $pl->{custom_fields} })
	{
		my ($s) = split /\./, $k;
		$consumed{"$s.$_"} = $k for @{ $pl->{custom_fields}{$k}{consumes} || [] };
	}

	# Walk the graph from the root. Dispatch wrappers and list element types
	# are edges too (that is the only way the concrete statement and variable
	# structs are reached), pointers to datum types are not (they are emitted
	# as dno references).
	my @order;
	my %reachable;
	my @queue = ($pl->{root});
	while (@queue)
	{
		my $s = shift @queue;
		next if $reachable{$s}++;
		push @order, $s;

		if ($dispatch{$s})
		{
			push @queue, map { $_->{struct} } @{ $dispatch{$s} };
			next;
		}

		my $si = $info->{$s} or die "struct $s is not in $pl->{header}\n";
		my $cfg = $pl->{structs}{$s}
		  or die "no plpgsql.structs entry for $s in overrides.pl (reachable from $pl->{root})\n";

		foreach my $f (@{ $cfg->{emit} })
		{
			my $t = $si->{field_types}{$f}
			  // die "$s.$f is listed in overrides.pl but not in $pl->{header}\n";
			$t =~ s/^struct\s+//;

			if ($pl->{arrays}{"$s.$f"})
			{
				push @queue, $1 if $t =~ /^(\w+)\*\*$/;
			}
			elsif ($pl->{linked_lists}{"$s.$f"})
			{
				push @queue, $1 if $t =~ /^(\w+)\*$/;
			}
			elsif ($pl->{custom_fields}{"$s.$f"})
			{
				# hand-written, no edges
			}
			elsif ($t eq 'List*')
			{
				push @queue, $list_elem->($s, $f);
			}
			elsif ($t =~ /^(\w+)\*$/ and $info->{$1} and not $datum_type{$1})
			{
				push @queue, $1;
			}
		}
	}

	# Every reachable struct must have all its fields accounted for, and
	# overrides.pl must not refer to anything that no longer exists
	foreach my $s (@order)
	{
		next if $dispatch{$s};
		my $cfg = $pl->{structs}{$s};
		my %seen;
		foreach my $f (@{ $cfg->{emit} }, @{ $cfg->{skip} || [] })
		{
			die "$s.$f is listed in overrides.pl but not in $pl->{header}\n"
			  unless exists $info->{$s}{field_types}{$f};
			die "$s.$f is listed more than once in overrides.pl\n" if $seen{$f}++;
			die "$s.$f is both emitted and consumed by $consumed{\"$s.$f\"} in overrides.pl\n"
			  if $consumed{"$s.$f"};
		}
		foreach my $f (@{ $info->{$s}{fields} })
		{
			next if $seen{$f} or $consumed{"$s.$f"};
			die "$s.$f ($info->{$s}{field_types}{$f}) is not classified in overrides.pl: add it to the emit or skip list of $s\n";
		}
	}
	foreach my $s (sort keys %{ $pl->{structs} })
	{
		die "plpgsql.structs entry $s in overrides.pl is not reachable from $pl->{root} (or is a dispatch wrapper)\n"
		  unless $reachable{$s} and not $dispatch{$s};
	}
	foreach my $k (sort keys %{ $pl->{arrays} }, keys %{ $pl->{linked_lists} }, keys %{ $pl->{custom_fields} })
	{
		my ($s, $f) = split /\./, $k;
		die "$k in overrides.pl is not an emitted field\n"
		  unless $reachable{$s} and elem $f, @{ $pl->{structs}{$s}{emit} || [] };
	}

	my $out_defs = '';
	my $out_impls = '';
	my $proto = $RESULT_MESSAGE . "\n";
	my %used_enums;
	my %srcdata_structs;

	foreach my $s (@order)
	{
		$out_defs .=
		  "static void _out$s(OUT_TYPE($s, $s) out_node, const $s *node);\n";

		if ($dispatch{$s})
		{
			# oneof wrapper: tags come from the enum values (plus one, since
			# proto field numbers start at 1), so that a new enum value
			# can't renumber the existing members. Several values may map to
			# the same struct (PLPGSQL_DTYPE_PROMISE => PLpgSQL_var).
			my $d = $pl->{dispatch}{$s};
			my (@members, %member_seen, @cases, %case_by_struct);
			foreach my $c (@{ $dispatch{$s} })
			{
				if (!$member_seen{ $c->{struct} }++)
				{
					push @members,
					  sprintf('    %s %s = %d [json_name="%s"];', $c->{struct},
						oneof_field($c->{struct}), $c->{value} + 1, $c->{struct});
					push @cases, $c->{struct};
				}
				push @{ $case_by_struct{ $c->{struct} } }, $c->{value_name};
			}

			# The oneof is named "node" like in the Node message. It must
			# not share a prefix with a member (oneof "stmt" + member
			# "stmt_case" would clash with the generated stmt_case() oneof
			# accessor of upb and C++).
			$proto .= "message $s\n{\n  oneof node {\n";
			$proto .= join("\n", @members) . "\n  }\n}\n\n";

			$out_impls .= "static void\n_out$s(OUT_TYPE($s, $s) out, const $s *node)\n{\n";
			$out_impls .= "  check_stack_depth();\n\n";
			$out_impls .= "  switch (node->$d->{tag_field})\n  {\n";
			foreach my $struct (@cases)
			{
				$out_impls .= "    case $_:\n" for @{ $case_by_struct{$struct} };
				$out_impls .= "      OUT_PLPGSQL_NODE($s, $struct, " . oneof_field($struct) . ");\n";
				$out_impls .= "      break;\n";
			}
			$out_impls .= "    default:\n";
			$out_impls .= "      elog(ERROR, \"unrecognized $d->{enum}: %d\", (int) node->$d->{tag_field});\n";
			$out_impls .= "  }\n}\n\n";

			$srcdata_structs{$s} = {
				fields => [
					{ name => $d->{tag_field}, c_type => $d->{enum} },
					map { { name => oneof_field($_), c_type => "$_*" } } @cases
				]
			};
			next;
		}

		my $si = $info->{$s};
		my $cfg = $pl->{structs}{$s};
		my $out = '';
		my $msg = '';
		my $field_no = 1;
		my @srcdata_fields;

		my $add = sub {
			my ($write_macro, $proto_type, $outname, $jsonname, $c_type) = @_;
			$out .= "  $write_macro;\n";
			$msg .= "  $proto_type $outname = $field_no [json_name=\"$jsonname\"];\n";
			$field_no++;
			push @srcdata_fields, { name => $jsonname, c_type => $c_type };
		};

		foreach my $f (@{ $cfg->{emit} })
		{
			my $t = $si->{field_types}{$f};
			$t =~ s/^struct\s+//;
			my $o = underscore($f);
			my $j = $f;

			if (my $count = $pl->{arrays}{"$s.$f"})
			{
				if ($t =~ /^(\w+)\*\*$/)
				{
					$add->("WRITE_PLPGSQL_PTR_ARRAY_FIELD($s, $1, $o, $j, $f, $count)",
						"repeated $1", $o, $j, "$1*[]");
				}
				elsif ($t =~ /^int(\*|\[\w+\])$/)
				{
					$add->("WRITE_PLPGSQL_INT_ARRAY_FIELD($s, $o, $j, $f, $count)",
						'repeated int32', $o, $j, 'int[]');
				}
				else
				{
					die "could not handle array type \"$t\" of $s.$f\n";
				}
			}
			elsif (my $next = $pl->{linked_lists}{"$s.$f"})
			{
				$t =~ /^(\w+)\*$/
				  or die "linked list $s.$f has non-pointer type \"$t\"\n";
				$add->("WRITE_PLPGSQL_LINKED_LIST_FIELD($s, $1, $o, $j, $f, $next)",
					"repeated $1", $o, $j, "$1*[]");
			}
			elsif (my $c = $pl->{custom_fields}{"$s.$f"})
			{
				$add->("WRITE_PLPGSQL_CUSTOM_FIELD($s, $c->{outname}, $c->{outname}, $f)",
					$c->{proto_type}, $c->{outname}, $c->{outname}, $c->{c_type});
			}
			elsif ($t =~ /^(\w+)\*$/ and $datum_type{$1})
			{
				# reference to a variable: its dno, or -1 if NULL
				$add->("WRITE_PLPGSQL_DATUM_REF_FIELD($s, ${o}_dno, ${j}_dno, $f)",
					'int32', "${o}_dno", "${j}_dno", 'int');
			}
			elsif ($t eq 'List*')
			{
				my $e = $list_elem->($s, $f);
				$add->("WRITE_PLPGSQL_LIST_FIELD($s, $e, $o, $j, $f)",
					"repeated $e", $o, $j, "$e*[]");
			}
			elsif ($t =~ /^(\w+)\*$/ and $info->{$1})
			{
				my $e = $1;
				die "$s.$f points to dispatch wrapper $e, which is only supported in lists and arrays\n"
				  if $dispatch{$e};
				$add->("WRITE_SPECIFIC_NODE_PTR_FIELD($s, $e, " . underscore($e) . ", $o, $j, $f)",
					$e, $o, $j, $t);
			}
			elsif ($t =~ /^(\w+)\*$/ and elem $1, @{ $ctx->{node_types} })
			{
				# a parse tree node (e.g. TypeName), handled by the regular
				# generated output functions
				my $e = $1;
				die "node type $e has an underscore in its name, so its output function is not _out$e\n"
				  if $e =~ /_/;
				$add->("WRITE_SPECIFIC_NODE_PTR_FIELD($s, $e, " . underscore($e) . ", $o, $j, $f)",
					$e, $o, $j, $t);
			}
			elsif (elem $t, @{ $pl->{as_int_types} || [] })
			{
				$add->("WRITE_INT_FIELD($s, $o, $j, $f)", 'int32', $o, $j, $t);
			}
			elsif (my @scalar = scalar_kind($t))
			{
				$add->("WRITE_$scalar[0]_FIELD($s, $o, $j, $f)", $scalar[1], $o, $j, $t);
			}
			elsif ($enum_members{$t})
			{
				$used_enums{$t} = 1;
				$add->("WRITE_ENUM_FIELD($s, $t, $o, $j, $f)", $t, $o, $j, $t);
			}
			elsif ($enum_known{$t})
			{
				# enum from the regular node headers (e.g. FetchDirection)
				$add->("WRITE_ENUM_FIELD($s, $t, $o, $j, $f)", $t, $o, $j, $t);
			}
			else
			{
				die "could not handle type \"$t\" of $s.$f for output (add it to the skip list of $s in overrides.pl to skip it)\n";
			}
		}

		$out_impls .= "static void\n_out$s(OUT_TYPE($s, $s) out, const $s *node)\n{\n$out}\n\n";
		$proto .= "message $s\n{\n$msg}\n\n";
		$srcdata_structs{$s} = { fields => \@srcdata_fields };
	}

	# Enum helpers for the PL/pgSQL enums actually used, into the same file
	# (so only the files including it need plpgsql.h), and their protobuf
	# definitions
	my (@enum_to_strings, @enum_to_ints, @int_to_enums, @proto_enums, @used_enum_names);
	foreach my $e (@header_enums)
	{
		next unless $used_enums{ $e->{name} };
		my $d = LibpgQuery::NodeSupport::Outfuncs::enum_defs($e->{name},
			[ map { $_->{name} } @{ $e->{members} } ],
			uc($e->{name}) . '_UNDEFINED');
		push @proto_enums, $d->{proto};
		push @enum_to_strings, $d->{to_string};
		push @enum_to_ints, $d->{to_int};
		push @int_to_enums, $d->{int_to_enum};
		push @used_enum_names, $e->{name};
	}
	$proto .= ($pl->{extra_proto} // '') . "\n" . join("\n\n", @proto_enums) . "\n";

	write_file("$ctx->{outdir}/pg_query_outfuncs_plpgsql_defs.c",
		$HEADER
		  . join("\n\n", @enum_to_strings, @enum_to_ints, @int_to_enums)
		  . "\n\n" . $out_defs . "\n\n" . $out_impls);

	(my $group = $pl->{header}) =~ s/^src\/include\///;
	$group =~ s/^src\///;
	$group =~ s/\.h$//;
	$group = "../$group";    # relative to src/include, like the other groups

	return {
		proto => $proto,
		srcdata => {
			struct_defs => { $group => \%srcdata_structs },
			enum_defs => {
				$group => {
					map { $_->{name} => { values => $_->{members} } } @header_enums
				}
			},
			enum_names => [ map { $_->{name} } @header_enums ],
		},
	};
}

1;
