/*-------------------------------------------------------------------------
 *
 * pg_authid_d.h
 *    Macro definitions for pg_authid
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_AUTHID_D_H
#define PG_AUTHID_D_H

#define AuthIdRelationId 1260
#define AuthIdRelation_Rowtype_Id 2842

#define Anum_pg_authid_rolname 1
#define Anum_pg_authid_rolsuper 2
#define Anum_pg_authid_rolinherit 3
#define Anum_pg_authid_rolcreaterole 4
#define Anum_pg_authid_rolcreatedb 5
#define Anum_pg_authid_rolcanlogin 6
#define Anum_pg_authid_rolreplication 7
#define Anum_pg_authid_rolbypassrls 8
#define Anum_pg_authid_rolconnlimit 9
#define Anum_pg_authid_rolpassword 10
#define Anum_pg_authid_rolvaliduntil 11

#define Natts_pg_authid 11

#define BOOTSTRAP_SUPERUSERID 10
#define DEFAULT_ROLE_MONITOR 3373
#define DEFAULT_ROLE_READ_ALL_SETTINGS 3374
#define DEFAULT_ROLE_READ_ALL_STATS 3375
#define DEFAULT_ROLE_STAT_SCAN_TABLES 3377
#define DEFAULT_ROLE_READ_SERVER_FILES 4569
#define DEFAULT_ROLE_WRITE_SERVER_FILES 4570
#define DEFAULT_ROLE_EXECUTE_SERVER_PROGRAM 4571
#define DEFAULT_ROLE_SIGNAL_BACKENDID 4200

#endif							/* PG_AUTHID_D_H */
