/*-------------------------------------------------------------------------
 *
 * pg_range_d.h
 *    Macro definitions for pg_range
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_RANGE_D_H
#define PG_RANGE_D_H

/* Macros related to the structure of pg_range */

#define RangeRelationId 3541
#define RangeTypidIndexId 3542
#define RangeMultirangeTypidIndexId 2228

#define Anum_pg_range_rngtypid 1
#define Anum_pg_range_rngsubtype 2
#define Anum_pg_range_rngmultitypid 3
#define Anum_pg_range_rngcollation 4
#define Anum_pg_range_rngsubopc 5
#define Anum_pg_range_rngcanonical 6
#define Anum_pg_range_rngsubdiff 7

#define Natts_pg_range 7

/* Definitions copied from pg_range.h */


/* OID symbols for objects defined in pg_range.dat */


#endif							/* PG_RANGE_D_H */
