/*-------------------------------------------------------------------------
 *
 * pg_ts_template_d.h
 *    Macro definitions for pg_ts_template
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TS_TEMPLATE_D_H
#define PG_TS_TEMPLATE_D_H

#define TSTemplateRelationId 3764

#define Anum_pg_ts_template_tmplname 1
#define Anum_pg_ts_template_tmplnamespace 2
#define Anum_pg_ts_template_tmplinit 3
#define Anum_pg_ts_template_tmpllexize 4

#define Natts_pg_ts_template 4


#endif							/* PG_TS_TEMPLATE_D_H */
