/*-------------------------------------------------------------------------
 *
 * pg_transform_d.h
 *    Macro definitions for pg_transform
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TRANSFORM_D_H
#define PG_TRANSFORM_D_H

#define TransformRelationId 3576

#define Anum_pg_transform_trftype 1
#define Anum_pg_transform_trflang 2
#define Anum_pg_transform_trffromsql 3
#define Anum_pg_transform_trftosql 4

#define Natts_pg_transform 4


#endif							/* PG_TRANSFORM_D_H */
