/*-------------------------------------------------------------------------
 *
 * pg_ts_config_d.h
 *    Macro definitions for pg_ts_config
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TS_CONFIG_D_H
#define PG_TS_CONFIG_D_H

#define TSConfigRelationId 3602

#define Anum_pg_ts_config_cfgname 1
#define Anum_pg_ts_config_cfgnamespace 2
#define Anum_pg_ts_config_cfgowner 3
#define Anum_pg_ts_config_cfgparser 4

#define Natts_pg_ts_config 4


#endif							/* PG_TS_CONFIG_D_H */
