// Autogenerated lightweight enum int->name lookups for the upb scan API.
#ifndef PG_QUERY_ENUM_NAMES_H
#define PG_QUERY_ENUM_NAMES_H
const char *pg_query_token_name(int value);
const char *pg_query_keyword_kind_name(int value);
#endif
