/*--------------------------------------------------------------------
 * Symbols referenced in this file:
 * - ScanKeywords
 * - ScanKeywords_kw_string
 * - ScanKeywords_kw_offsets
 * - ScanKeywords_hash_func
 *--------------------------------------------------------------------
 */

/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "common/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absent\0"
	"absolute\0"
	"access\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"bit\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compression\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"day\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"detach\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"distkey\0"
	"distribute\0"
	"distributed\0"
	"diststyle\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"each\0"
	"else\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"enum\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"explain\0"
	"expression\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"having\0"
	"header\0"
	"hold\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"indent\0"
	"index\0"
	"indexes\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"json\0"
	"json_array\0"
	"json_arrayagg\0"
	"json_object\0"
	"json_objectagg\0"
	"key\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"mapping\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxvalue\0"
	"merge\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"mode\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"node\0"
	"none\0"
	"normalize\0"
	"normalized\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"numeric\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"parallel\0"
	"parameter\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"placing\0"
	"plans\0"
	"policy\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"publication\0"
	"quote\0"
	"randomly\0"
	"range\0"
	"read\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rows\0"
	"rule\0"
	"savepoint\0"
	"scalar\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"sql\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"step\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"volatile\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	13,
	22,
	29,
	36,
	40,
	46,
	52,
	62,
	66,
	71,
	77,
	84,
	92,
	100,
	104,
	108,
	114,
	117,
	121,
	132,
	142,
	153,
	164,
	167,
	174,
	181,
	191,
	205,
	214,
	221,
	227,
	235,
	242,
	249,
	253,
	261,
	266,
	274,
	277,
	283,
	288,
	295,
	303,
	312,
	317,
	322,
	330,
	336,
	341,
	351,
	367,
	373,
	384,
	390,
	396,
	404,
	413,
	421,
	431,
	438,
	446,
	454,
	463,
	470,
	480,
	492,
	505,
	519,
	528,
	539,
	550,
	562,
	570,
	579,
	590,
	595,
	600,
	607,
	613,
	617,
	622,
	630,
	646,
	659,
	672,
	687,
	700,
	718,
	731,
	738,
	744,
	749,
	758,
	762,
	773,
	777,
	785,
	793,
	801,
	810,
	821,
	830,
	838,
	845,
	855,
	866,
	874,
	880,
	885,
	892,
	903,
	911,
	919,
	928,
	936,
	947,
	959,
	969,
	972,
	981,
	988,
	995,
	1000,
	1005,
	1010,
	1017,
	1026,
	1036,
	1040,
	1045,
	1052,
	1058,
	1065,
	1073,
	1083,
	1093,
	1101,
	1108,
	1116,
	1127,
	1137,
	1146,
	1154,
	1160,
	1167,
	1173,
	1180,
	1189,
	1195,
	1201,
	1211,
	1215,
	1221,
	1229,
	1236,
	1244,
	1251,
	1256,
	1261,
	1270,
	1280,
	1290,
	1297,
	1303,
	1311,
	1320,
	1326,
	1335,
	1342,
	1350,
	1357,
	1364,
	1369,
	1374,
	1383,
	1386,
	1392,
	1402,
	1412,
	1421,
	1428,
	1431,
	1439,
	1449,
	1459,
	1466,
	1472,
	1480,
	1488,
	1497,
	1507,
	1514,
	1520,
	1526,
	1532,
	1544,
	1551,
	1559,
	1563,
	1571,
	1581,
	1590,
	1595,
	1603,
	1606,
	1613,
	1623,
	1628,
	1633,
	1644,
	1658,
	1670,
	1685,
	1689,
	1694,
	1700,
	1709,
	1715,
	1720,
	1728,
	1736,
	1746,
	1752,
	1757,
	1763,
	1768,
	1774,
	1781,
	1786,
	1792,
	1802,
	1817,
	1826,
	1831,
	1838,
	1845,
	1853,
	1859,
	1867,
	1880,
	1889,
	1895,
	1902,
	1909,
	1918,
	1923,
	1929,
	1934,
	1939,
	1945,
	1954,
	1962,
	1968,
	1972,
	1977,
	1981,
	1985,
	1990,
	1995,
	1998,
	2003,
	2008,
	2018,
	2029,
	2033,
	2041,
	2048,
	2056,
	2063,
	2068,
	2075,
	2081,
	2089,
	2096,
	2099,
	2103,
	2110,
	2115,
	2119,
	2122,
	2127,
	2136,
	2143,
	2151,
	2154,
	2160,
	2171,
	2178,
	2182,
	2188,
	2193,
	2202,
	2210,
	2221,
	2227,
	2233,
	2242,
	2252,
	2259,
	2267,
	2277,
	2288,
	2296,
	2305,
	2313,
	2319,
	2326,
	2335,
	2345,
	2355,
	2363,
	2372,
	2381,
	2389,
	2395,
	2406,
	2417,
	2427,
	2438,
	2446,
	2458,
	2464,
	2473,
	2479,
	2484,
	2489,
	2498,
	2506,
	2516,
	2520,
	2531,
	2543,
	2551,
	2559,
	2568,
	2576,
	2583,
	2594,
	2602,
	2610,
	2616,
	2624,
	2633,
	2640,
	2650,
	2658,
	2665,
	2671,
	2676,
	2685,
	2692,
	2700,
	2709,
	2713,
	2718,
	2723,
	2733,
	2740,
	2747,
	2755,
	2762,
	2769,
	2776,
	2785,
	2792,
	2801,
	2811,
	2824,
	2831,
	2839,
	2852,
	2856,
	2862,
	2867,
	2873,
	2878,
	2886,
	2893,
	2898,
	2907,
	2916,
	2921,
	2925,
	2932,
	2943,
	2949,
	2959,
	2970,
	2976,
	2983,
	2988,
	2996,
	3003,
	3010,
	3016,
	3029,
	3039,
	3047,
	3057,
	3063,
	3070,
	3082,
	3088,
	3095,
	3107,
	3118,
	3123,
	3132,
	3142,
	3147,
	3152,
	3157,
	3162,
	3172,
	3175,
	3184,
	3196,
	3206,
	3212,
	3220,
	3225,
	3230,
	3239,
	3247,
	3252,
	3258,
	3266,
	3276,
	3288,
	3300,
	3306,
	3313,
	3321,
	3330,
	3339,
	3345,
	3352,
	3357,
	3363,
	3370,
	3376,
	3385,
	3395,
	3401,
	3408,
	3416,
	3425,
	3433,
	3441,
	3449,
	3454,
	3460,
	3469,
	3474,
	3480,
	3491,
	3498,
	3503,
	3510,
	3518,
	3523,
	3531,
	3537,
	3541,
	3555,
	3565,
	3576,
	3586,
	3596,
	3610,
	3619,
	3625,
	3633,
	3646,
	3655,
	3660,
	3664,
};

#define SCANKEYWORDS_NUM_KEYWORDS 479

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[959] = {
		32767, 32767, -272,  32767, 32767, 81,    0,     447,
		32767, 32767, 38,    294,   32767, 32767, 336,   233,
		0,     248,   32767, 154,   32767, 32767, -16,   45,
		32767, 32767, 32767, 290,   -632,  0,     -78,   442,
		80,    84,    93,    32767, -220,  80,    32767, 262,
		32767, 128,   68,    215,   32767, 881,   32767, 392,
		32767, 471,   167,   32767, 191,   32767, 0,     339,
		1024,  0,     0,     -252,  -206,  97,    -403,  140,
		-25,   32767, -18,   32767, 0,     0,     444,   0,
		0,     0,     32767, 32767, 32767, 449,   32767, 0,
		32767, 32767, 246,   0,     117,   0,     32767, -596,
		32767, 32767, 1069,  32767, 32767, 15,    32767, -152,
		39,    32767, 32767, 135,   32767, 216,   32767, 811,
		-13,   32767, 32767, 223,   32767, 32767, 380,   24,
		195,   -3,    32767, 0,     32767, 32767, -72,   32767,
		142,   32767, 174,   -481,  606,   49,    0,     300,
		32767, 590,   -344,  32767, -330,  -136,  32767, 32767,
		411,   333,   32767, 94,    32767, 32767, 32767, 314,
		32767, 453,   32767, -193,  32767, 32767, 336,   -87,
		0,     570,   32767, -87,   132,   24,    26,    32767,
		169,   239,   224,   32767, 0,     415,   -173,  240,
		54,    0,     0,     32767, 90,    28,    32767, 32767,
		32767, 0,     32767, 188,   -26,   32767, 32767, 421,
		32767, 0,     32767, 138,   32767, 157,   32767, 394,
		226,   32767, 0,     106,   -14,   32767, 32767, 125,
		0,     990,   32767, 32767, 274,   697,   451,   447,
		46,    32767, 298,   175,   393,   250,   32767, 32767,
		0,     32767, 32767, 0,     -349,  32767, 740,   1276,
		452,   0,     32767, 32767, -127,  32767, 32767, -1125,
		-330,  15,    -102,  176,   57,    32767, 189,   -211,
		-39,   0,     78,    -930,  1094,  32767, 139,   494,
		524,   32767, -689,  -7,    102,   -11,   0,     -246,
		605,   3,     0,     412,   240,   -234,  757,   0,
		344,   32767, 32767, 32767, 166,   45,    137,   178,
		0,     32767, 0,     32767, -124,  1328,  32767, 368,
		0,     371,   79,    77,    326,   32767, 155,   32767,
		32767, 32767, 274,   0,     32767, 0,     147,   16,
		454,   32767, 32767, 287,   0,     32767, 777,   73,
		231,   103,   0,     -8,    467,   0,     32767, -134,
		32767, -216,  14,    0,     32767, -530,  653,   -326,
		32767, 44,    272,   32767, 32767, 401,   32767, 32767,
		32767, 32767, 32767, 32767, 0,     -158,  32767, 0,
		32767, 32767, 32767, 32767, 289,   386,   32767, -210,
		32767, 32767, 0,     32767, 363,   0,     284,   0,
		-289,  -144,  483,   32767, 0,     32767, 212,   2,
		32767, -137,  244,   32767, 32767, 1208,  32767, 32767,
		32767, 0,     38,    32767, -319,  -43,   32767, 179,
		331,   32767, 276,   32767, 126,   163,   552,   413,
		92,    171,   37,    293,   381,   192,   32767, 431,
		56,    -499,  259,   416,   112,   365,   32767, 32767,
		0,     266,   226,   263,   455,   -386,  11,    0,
		32767, 362,   -157,  0,     32767, -504,  -633,  404,
		950,   604,   237,   463,   32767, 32767, 0,     364,
		32767, 29,    256,   509,   498,   236,   728,   320,
		32767, -443,  32767, 365,   127,   302,   32767, 32767,
		32767, 348,   32767, 32767, 32767, 32767, 0,     32767,
		-80,   0,     -26,   0,     177,   32767, 32767, 278,
		32767, 0,     67,    32767, 32767, 199,   -778,  32767,
		-64,   317,   32767, 0,     145,   0,     515,   403,
		409,   374,   32767, 32767, 32767, -438,  -775,  170,
		-434,  79,    32767, 0,     32767, 32767, 32767, 32767,
		32767, 0,     288,   32767, 0,     32767, 0,     875,
		0,     234,   80,    -249,  -78,   211,   32767, 141,
		136,   32767, 899,   0,     32767, 32767, 32767, 0,
		32767, 430,   32767, 32767, 429,   32767, -281,  32767,
		32767, 32767, 0,     32767, 255,   428,   32767, 0,
		32767, -515,  274,   32767, 32767, 150,   35,    372,
		32767, 32767, 32767, 55,    18,    442,   32767, 32767,
		0,     -116,  -317,  0,     32767, 0,     -505,  0,
		32767, 32767, -43,   -115,  230,   301,   -193,  181,
		-210,  96,    394,   0,     32767, 32767, -96,   32767,
		32767, 99,    120,   33,    219,   32767, 32767, 32767,
		-128,  32767, 0,     224,   340,   0,     0,     -4,
		-135,  -140,  223,   34,    32767, 471,   32767, -208,
		209,   478,   32,    207,   32767, 298,   32767, 32767,
		109,   227,   -434,  32767, 251,   327,   -141,  0,
		48,    32767, 0,     3,     912,   0,     32767, 448,
		32767, 402,   133,   0,     32767, 32767, 32767, 32767,
		32767, 32767, 32767, 32767, 0,     32767, 32767, -201,
		32767, 0,     245,   32767, 32767, 613,   207,   32767,
		-222,  32767, 32767, 330,   -800,  32767, -196,  32767,
		32767, 623,   172,   52,    0,     32767, 32767, 414,
		32767, -60,   421,   32767, 32767, 32767, 32767, 47,
		32767, 0,     397,   360,   32767, 32767, 32767, 32767,
		419,   -101,  32767, 32767, 32767, 54,    -537,  32767,
		0,     32767, 32767, 0,     529,   350,   -515,  235,
		0,     32767, 892,   0,     181,   32767, 32767, 32767,
		0,     32767, 387,   0,     257,   -97,   32767, 329,
		-274,  32767, 32767, 478,   -231,  50,    0,     395,
		396,   -529,  32767, 32767, 192,   443,   62,    347,
		0,     0,     32767, 0,     -194,  32767, 787,   -149,
		0,     294,   282,   436,   0,     456,   190,   32767,
		138,   32767, 32767, 1033,  193,   0,     32767, 32767,
		195,   305,   32767, 167,   32767, 0,     32767, 32767,
		193,   32767, 32767, 0,     0,     64,    39,    -63,
		35,    475,   0,     32767, 32767, 0,     48,    873,
		135,   465,   521,   459,   32767, 32767, -130,  32767,
		-347,  32767, -387,  0,     32767, -188,  250,   0,
		0,     32767, 0,     103,   32767, 313,   32767, 0,
		0,     109,   186,   34,    32767, 10,    147,   32767,
		32767, 32767, 115,   32767, 32767, -362,  0,     324,
		26,    32767, 32767, 32767, 46,    0,     32767, 32767,
		32767, 14,    275,   32767, -822,  97,    -28,   -228,
		32767, 0,     280,   -1123, 82,    -856,  285,   232,
		258,   32767, 387,   32767, 323,   32767, 392,   286,
		-548,  32767, 0,     0,     32767, 32767, 302,   0,
		172,   451,   -27,   -73,   0,     152,   32767, 32767,
		32767, 0,     468,   32767, 32767, 0,     461,   221,
		99,    0,     32767, 32767, 32767, 0,     39,    -78,
		248,   55,    32767, 0,     652,   119,   32767, 32767,
		514,   32767, 407,   293,   32767, 298,   0,     303,
		305,   0,     32767, 0,     32767, 32767, 253,   0,
		32767, 0,     0,     638,   32767, 280,   0,     -215,
		32767, 73,    32767, 0,     -56,   366,   0,     32767,
		32767, 32767, 0,     -2,    32767, 32767, 32767, 87,
		32767, 32767, 164,   41,    32767, 32767, 32767, -281,
		0,     299,   32767, 277,   357,   32767, 381,   211,
		1112,  32767, 585,   32767, 558,   -319,  0,     557,
		361,   105,   236,   32767, 281,   198,   32767, 32767,
		32767, 356,   218,   238,   32767, 0,     32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 17 + c;
	}
	return h[a % 959] + h[b % 959];
}

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	17
};

#endif							/* KWLIST_D_H */
