/*
 * pg_query_parse_plpgsql_protobuf.c
 *
 * Public API for parsing PL/pgSQL to protobuf format.
 * This file is autogenerated by ./scripts/generate_plpgsql_protobuf.rb
 */

#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>

#include "pg_query.h"
#include "pg_query_internal.h"
#include "pg_query_json_plpgsql.h"

#include <assert.h>
#include <catalog/pg_type.h>
#include <catalog/objectaddress.h>
#include <catalog/pg_proc.h>
#include <nodes/parsenodes.h>
#include <nodes/nodeFuncs.h>

#include "protobuf/pg_query.pb-c.h"

// Include generated outfuncs macros
#include "pg_query_outfuncs_plpgsql.c"

typedef struct {
  PLpgSQL_function *func;
  PgQueryError* error;
} PgQueryInternalPlpgsqlFuncAndError;

/* Forward declaration from pg_query_parse_plpgsql.c */
extern PgQueryInternalPlpgsqlFuncAndError pg_query_raw_parse_plpgsql(Node* stmt);

typedef struct plStmts
{
  Node **stmts;
  int stmts_buf_size;
  int stmts_count;
} plStmts;

static bool stmts_walker(Node *node, plStmts *state)
{
  bool result;
  MemoryContext ccxt = CurrentMemoryContext;

  if (node == NULL) return false;

  if (IsA(node, CreateFunctionStmt) || IsA(node, DoStmt))
  {
    if (state->stmts_count >= state->stmts_buf_size)
    {
      state->stmts_buf_size *= 2;
      state->stmts = (Node**) repalloc(state->stmts, state->stmts_buf_size * sizeof(Node*));
    }
    state->stmts[state->stmts_count] = (Node *) node;
    state->stmts_count++;
  } else if (IsA(node, RawStmt)) {
    return stmts_walker((Node *) ((RawStmt *) node)->stmt, state);
  }

  PG_TRY();
  {
    result = raw_expression_tree_walker(node, stmts_walker, (void*) state);
  }
  PG_CATCH();
  {
    MemoryContextSwitchTo(ccxt);
    FlushErrorState();
    result = false;
  }
  PG_END_TRY();

  return result;
}

PgQueryPlpgsqlProtobufParseResult pg_query_parse_plpgsql_protobuf(const char* input)
{
  MemoryContext ctx = NULL;
  PgQueryPlpgsqlProtobufParseResult result = {0};
  PgQueryInternalParsetreeAndError parse_result;
  plStmts statements;
  size_t i;
  PgQuery__PLpgSQLParseResult *parse_result_msg;

  ctx = pg_query_enter_memory_context();

  /* Parse the SQL input first to find CREATE FUNCTION/DO statements */
  parse_result = pg_query_raw_parse(input, PG_QUERY_PARSE_DEFAULT);
  result.error = parse_result.error;
  if (result.error != NULL) {
    pg_query_exit_memory_context(ctx);
    return result;
  }

  statements.stmts_buf_size = 100;
  statements.stmts = (Node**) palloc(statements.stmts_buf_size * sizeof(Node*));
  statements.stmts_count = 0;

  stmts_walker((Node*) parse_result.tree, &statements);

  /* Create the protobuf result message */
  parse_result_msg = palloc0(sizeof(PgQuery__PLpgSQLParseResult));
  pg_query__plpg_sqlparse_result__init(parse_result_msg);
  parse_result_msg->version = PG_VERSION_NUM;

  if (statements.stmts_count == 0) {
    parse_result_msg->n_plpgsql_funcs = 0;
    parse_result_msg->plpgsql_funcs = NULL;
  } else {
    parse_result_msg->n_plpgsql_funcs = statements.stmts_count;
    parse_result_msg->plpgsql_funcs = palloc0(statements.stmts_count * sizeof(PgQuery__PLpgSQLFunction*));

    for (i = 0; i < statements.stmts_count; i++) {
      PgQueryInternalPlpgsqlFuncAndError func_and_error;

      func_and_error = pg_query_raw_parse_plpgsql(statements.stmts[i]);

      result.error = func_and_error.error;
      if (result.error != NULL) {
        pg_query_exit_memory_context(ctx);
        return result;
      }

      if (func_and_error.func != NULL) {
        parse_result_msg->plpgsql_funcs[i] = palloc0(sizeof(PgQuery__PLpgSQLFunction));
        pg_query__plpg_sql_function__init(parse_result_msg->plpgsql_funcs[i]);
        _outPLpgSQL_function(parse_result_msg->plpgsql_funcs[i], func_and_error.func);
        plpgsql_free_function_memory(func_and_error.func);
      }
    }
  }

  /* Pack the protobuf message */
  result.parse_tree.len = pg_query__plpg_sqlparse_result__get_packed_size(parse_result_msg);
  result.parse_tree.data = malloc(result.parse_tree.len);
  pg_query__plpg_sqlparse_result__pack(parse_result_msg, (uint8_t*) result.parse_tree.data);

  /* Copy stderr buffer if present */
  if (parse_result.stderr_buffer != NULL) {
    result.stderr_buffer = strdup(parse_result.stderr_buffer);
    free(parse_result.stderr_buffer);
  }

  pg_query_exit_memory_context(ctx);

  return result;
}

void pg_query_free_plpgsql_protobuf_parse_result(PgQueryPlpgsqlProtobufParseResult result)
{
  if (result.error) {
    pg_query_free_error(result.error);
  }

  if (result.parse_tree.data) {
    free(result.parse_tree.data);
  }

  if (result.stderr_buffer) {
    free(result.stderr_buffer);
  }
}

char* pg_query_plpgsql_protobuf_to_json(PgQueryProtobuf protobuf)
{
  MemoryContext ctx = NULL;
  PgQuery__PLpgSQLParseResult *parse_result;
  char *json_result;
  size_t i;
  size_t json_len;

  ctx = pg_query_enter_memory_context();

  /* Unpack the protobuf */
  parse_result = pg_query__plpg_sqlparse_result__unpack(NULL,
    protobuf.len, (const uint8_t*) protobuf.data);

  if (parse_result == NULL) {
    pg_query_exit_memory_context(ctx);
    return strdup("[]");
  }

  if (parse_result->n_plpgsql_funcs == 0) {
    pg_query__plpg_sqlparse_result__free_unpacked(parse_result, NULL);
    pg_query_exit_memory_context(ctx);
    return strdup("[]");
  }

  /* Build JSON array - reuse existing JSON conversion by converting back to PLpgSQL_function */
  json_result = strdup("[\n");

  for (i = 0; i < parse_result->n_plpgsql_funcs; i++) {
    PLpgSQL_function *func;
    char *func_json;
    char *new_out;
    size_t new_out_len;

    func = _readPLpgSQL_function(parse_result->plpgsql_funcs[i]);
    func_json = plpgsqlToJSON(func);

    new_out_len = strlen(json_result) + strlen(func_json) + 3;
    new_out = malloc(new_out_len);
    snprintf(new_out, new_out_len, "%s%s,\n", json_result, func_json);
    free(json_result);
    pfree(func_json);
    json_result = new_out;
  }

  /* Fix trailing comma */
  json_len = strlen(json_result);
  if (json_len >= 2) {
    json_result[json_len - 2] = '\n';
    json_result[json_len - 1] = ']';
  }

  pg_query__plpg_sqlparse_result__free_unpacked(parse_result, NULL);
  pg_query_exit_memory_context(ctx);

  return json_result;
}
