/*
 * pg_query_outfuncs_plpgsql.c
 *
 * PLpgSQL to protobuf serialization.
 * This file is autogenerated by ./scripts/generate_plpgsql_protobuf.rb
 */

#include "pg_query.h"
#include "pg_query_internal.h"

#include <plpgsql.h>

#include "protobuf/pg_query.pb-c.h"

// Macros for writing PLpgSQL fields to protobuf
#define WRITE_BOOL_FIELD(outname, json_name, field) \
  out->outname = node->field

#define WRITE_INT_FIELD(outname, json_name, field) \
  out->outname = node->field

#define WRITE_LONG_FIELD(outname, json_name, field) \
  out->outname = node->field

#define WRITE_STRING_FIELD(outname, json_name, field) \
  if (node->field != NULL) out->outname = pstrdup(node->field)

#define WRITE_CHAR_FIELD(outname, json_name, field) \
  { char buf[2] = {node->field, '\0'}; out->outname = pstrdup(buf); }

#define WRITE_PLPGSQL_ENUM_FIELD(enum_type, outname, field) \
  out->outname = _plpgsqlEnumToInt##enum_type(node->field)

#define WRITE_PLPGSQL_EXPR_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLExpr)); \
    pg_query__plpg_sql_expr__init(out->outname); \
    _outPLpgSQL_expr(out->outname, node->field); \
  }

#define WRITE_PLPGSQL_TYPE_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLType)); \
    pg_query__plpg_sql_type__init(out->outname); \
    _outPLpgSQL_type(out->outname, node->field); \
  }

#define WRITE_PLPGSQL_VAR_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLVar)); \
    pg_query__plpg_sql_var__init(out->outname); \
    _outPLpgSQL_var(out->outname, node->field); \
  }

#define WRITE_PLPGSQL_DATUM_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLDatum)); \
    pg_query__plpg_sql_datum__init(out->outname); \
    _outPLpgSQL_datum(out->outname, (PLpgSQL_datum *) node->field); \
  }

#define WRITE_PLPGSQL_CONDITION_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLCondition)); \
    pg_query__plpg_sql_condition__init(out->outname); \
    _outPLpgSQL_condition(out->outname, node->field); \
  }

#define WRITE_PLPGSQL_EXCEPTION_BLOCK_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLExceptionBlock)); \
    pg_query__plpg_sql_exception_block__init(out->outname); \
    _outPLpgSQL_exception_block(out->outname, node->field); \
  }

#define WRITE_PLPGSQL_STMT_BLOCK_FIELD(outname, field) \
  if (node->field != NULL) { \
    out->outname = palloc0(sizeof(PgQuery__PLpgSQLStmtBlock)); \
    pg_query__plpg_sql_stmt_block__init(out->outname); \
    _outPLpgSQL_stmt_block(out->outname, node->field); \
  }

#define WRITE_PLPGSQL_STMT_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLStmt*)); \
    foreach(lc, node->field) { \
      PLpgSQL_stmt *stmt = (PLpgSQL_stmt *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLStmt)); \
      pg_query__plpg_sql_stmt__init(out->outname[i]); \
      _outPLpgSQL_stmt(out->outname[i], stmt); \
      i++; \
    } \
  }

#define WRITE_PLPGSQL_EXCEPTION_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLException*)); \
    foreach(lc, node->field) { \
      PLpgSQL_exception *exc = (PLpgSQL_exception *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLException)); \
      pg_query__plpg_sql_exception__init(out->outname[i]); \
      _outPLpgSQL_exception(out->outname[i], exc); \
      i++; \
    } \
  }

#define WRITE_PLPGSQL_IF_ELSIF_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLIfElsif*)); \
    foreach(lc, node->field) { \
      PLpgSQL_if_elsif *elsif = (PLpgSQL_if_elsif *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLIfElsif)); \
      pg_query__plpg_sql_if_elsif__init(out->outname[i]); \
      _outPLpgSQL_if_elsif(out->outname[i], elsif); \
      i++; \
    } \
  }

#define WRITE_PLPGSQL_CASE_WHEN_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLCaseWhen*)); \
    foreach(lc, node->field) { \
      PLpgSQL_case_when *when = (PLpgSQL_case_when *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLCaseWhen)); \
      pg_query__plpg_sql_case_when__init(out->outname[i]); \
      _outPLpgSQL_case_when(out->outname[i], when); \
      i++; \
    } \
  }

#define WRITE_PLPGSQL_DIAG_ITEM_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLDiagItem*)); \
    foreach(lc, node->field) { \
      PLpgSQL_diag_item *item = (PLpgSQL_diag_item *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLDiagItem)); \
      pg_query__plpg_sql_diag_item__init(out->outname[i]); \
      _outPLpgSQL_diag_item(out->outname[i], item); \
      i++; \
    } \
  }

#define WRITE_PLPGSQL_EXPR_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLExpr*)); \
    foreach(lc, node->field) { \
      PLpgSQL_expr *expr = (PLpgSQL_expr *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLExpr)); \
      pg_query__plpg_sql_expr__init(out->outname[i]); \
      _outPLpgSQL_expr(out->outname[i], expr); \
      i++; \
    } \
  }

#define WRITE_PLPGSQL_RAISE_OPTION_LIST_FIELD(outname, field) \
  if (node->field != NIL) { \
    ListCell *lc; \
    int i = 0; \
    out->n_##outname = list_length(node->field); \
    out->outname = palloc0(out->n_##outname * sizeof(PgQuery__PLpgSQLRaiseOption*)); \
    foreach(lc, node->field) { \
      PLpgSQL_raise_option *opt = (PLpgSQL_raise_option *) lfirst(lc); \
      out->outname[i] = palloc0(sizeof(PgQuery__PLpgSQLRaiseOption)); \
      pg_query__plpg_sql_raise_option__init(out->outname[i]); \
      _outPLpgSQL_raise_option(out->outname[i], opt); \
      i++; \
    } \
  }

#define WRITE_INT_ARRAY_FIELD(outname, field, count_field) \
  if (node->field != NULL && node->count_field > 0) { \
    int i; \
    out->n_##outname = node->count_field; \
    out->outname = palloc0(out->n_##outname * sizeof(int32_t)); \
    for (i = 0; i < node->count_field; i++) { \
      out->outname[i] = node->field[i]; \
    } \
  }

#define WRITE_STRING_ARRAY_FIELD(outname, field, count_field) \
  if (node->field != NULL && node->count_field > 0) { \
    int i; \
    out->n_##outname = node->count_field; \
    out->outname = palloc0(out->n_##outname * sizeof(char*)); \
    for (i = 0; i < node->count_field; i++) { \
      if (node->field[i] != NULL) \
        out->outname[i] = pstrdup(node->field[i]); \
    } \
  }

// READ macros for deserialization

#define READ_BOOL_FIELD(protoname, field) \
  node->field = msg->protoname

#define READ_INT_FIELD(protoname, field) \
  node->field = msg->protoname

#define READ_LONG_FIELD(protoname, field) \
  node->field = msg->protoname

#define READ_STRING_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = pstrdup(msg->protoname)

#define READ_CHAR_FIELD(protoname, field) \
  if (msg->protoname != NULL && msg->protoname[0] != '\0') node->field = msg->protoname[0]

#define READ_PLPGSQL_ENUM_FIELD(enum_type, protoname, field) \
  node->field = _plpgsqlIntToEnum##enum_type(msg->protoname)

#define READ_PLPGSQL_EXPR_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = _readPLpgSQL_expr(msg->protoname)

#define READ_PLPGSQL_TYPE_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = _readPLpgSQL_type(msg->protoname)

#define READ_PLPGSQL_VAR_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = _readPLpgSQL_var(msg->protoname)

#define READ_PLPGSQL_DATUM_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = (PLpgSQL_variable *) _readPLpgSQL_datum(msg->protoname)

#define READ_PLPGSQL_CONDITION_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = _readPLpgSQL_condition(msg->protoname)

#define READ_PLPGSQL_EXCEPTION_BLOCK_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = _readPLpgSQL_exception_block(msg->protoname)

#define READ_PLPGSQL_STMT_BLOCK_FIELD(protoname, field) \
  if (msg->protoname != NULL) node->field = _readPLpgSQL_stmt_block(msg->protoname)

#define READ_PLPGSQL_STMT_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_stmt *stmt = _readPLpgSQL_stmt(msg->protoname[i]); \
      node->field = lappend(node->field, stmt); \
    } \
  }

#define READ_PLPGSQL_EXCEPTION_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_exception *exc = _readPLpgSQL_exception(msg->protoname[i]); \
      node->field = lappend(node->field, exc); \
    } \
  }

#define READ_PLPGSQL_IF_ELSIF_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_if_elsif *elsif = _readPLpgSQL_if_elsif(msg->protoname[i]); \
      node->field = lappend(node->field, elsif); \
    } \
  }

#define READ_PLPGSQL_CASE_WHEN_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_case_when *when = _readPLpgSQL_case_when(msg->protoname[i]); \
      node->field = lappend(node->field, when); \
    } \
  }

#define READ_PLPGSQL_DIAG_ITEM_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_diag_item *item = _readPLpgSQL_diag_item(msg->protoname[i]); \
      node->field = lappend(node->field, item); \
    } \
  }

#define READ_PLPGSQL_EXPR_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_expr *expr = _readPLpgSQL_expr(msg->protoname[i]); \
      node->field = lappend(node->field, expr); \
    } \
  }

#define READ_PLPGSQL_RAISE_OPTION_LIST_FIELD(protoname, field) \
  if (msg->n_##protoname > 0) { \
    int i; \
    node->field = NIL; \
    for (i = 0; i < msg->n_##protoname; i++) { \
      PLpgSQL_raise_option *opt = _readPLpgSQL_raise_option(msg->protoname[i]); \
      node->field = lappend(node->field, opt); \
    } \
  }

// Include generated enum conversion functions
#include "include/pg_query_plpgsql_enum_defs.c"

// Include generated outfuncs definitions
#include "include/pg_query_outfuncs_plpgsql_defs.c"

// Include generated readfuncs definitions
#include "include/pg_query_readfuncs_plpgsql_defs.c"

// Public API
PgQueryProtobuf
pg_query_plpgsql_funcs_to_protobuf(PLpgSQL_function **funcs, int nfuncs)
{
  PgQueryProtobuf protobuf = {0};
  int i;
  PgQuery__PLpgSQLParseResult parse_result = PG_QUERY__PLPG_SQLPARSE_RESULT__INIT;

  parse_result.version = PG_VERSION_NUM;

  if (funcs == NULL || nfuncs == 0)
  {
    parse_result.n_plpgsql_funcs = 0;
    parse_result.plpgsql_funcs = NULL;
  }
  else
  {
    parse_result.n_plpgsql_funcs = nfuncs;
    parse_result.plpgsql_funcs = palloc(sizeof(PgQuery__PLpgSQLFunction*) * nfuncs);

    for (i = 0; i < nfuncs; i++)
    {
      parse_result.plpgsql_funcs[i] = palloc(sizeof(PgQuery__PLpgSQLFunction));
      pg_query__plpg_sql_function__init(parse_result.plpgsql_funcs[i]);
      _outPLpgSQL_function(parse_result.plpgsql_funcs[i], funcs[i]);
    }
  }

  protobuf.len = pg_query__plpg_sqlparse_result__get_packed_size(&parse_result);
  protobuf.data = malloc(sizeof(char) * protobuf.len);
  pg_query__plpg_sqlparse_result__pack(&parse_result, (void*) protobuf.data);

  return protobuf;
}
