// This file is autogenerated by ./scripts/generate_plpgsql_protobuf.rb

static int
_plpgsqlEnumToIntPLpgSQL_nsitem_type(PLpgSQL_nsitem_type value) {
  switch(value) {
    case PLPGSQL_NSTYPE_LABEL: return 1;
    case PLPGSQL_NSTYPE_VAR: return 2;
    case PLPGSQL_NSTYPE_REC: return 3;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_label_type(PLpgSQL_label_type value) {
  switch(value) {
    case PLPGSQL_LABEL_BLOCK: return 1;
    case PLPGSQL_LABEL_LOOP: return 2;
    case PLPGSQL_LABEL_OTHER: return 3;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_datum_type(PLpgSQL_datum_type value) {
  switch(value) {
    case PLPGSQL_DTYPE_VAR: return 1;
    case PLPGSQL_DTYPE_ROW: return 2;
    case PLPGSQL_DTYPE_REC: return 3;
    case PLPGSQL_DTYPE_RECFIELD: return 4;
    case PLPGSQL_DTYPE_PROMISE: return 5;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_promise_type(PLpgSQL_promise_type value) {
  switch(value) {
    case PLPGSQL_PROMISE_NONE: return 1;
    case PLPGSQL_PROMISE_TG_NAME: return 2;
    case PLPGSQL_PROMISE_TG_WHEN: return 3;
    case PLPGSQL_PROMISE_TG_LEVEL: return 4;
    case PLPGSQL_PROMISE_TG_OP: return 5;
    case PLPGSQL_PROMISE_TG_RELID: return 6;
    case PLPGSQL_PROMISE_TG_TABLE_NAME: return 7;
    case PLPGSQL_PROMISE_TG_TABLE_SCHEMA: return 8;
    case PLPGSQL_PROMISE_TG_NARGS: return 9;
    case PLPGSQL_PROMISE_TG_ARGV: return 10;
    case PLPGSQL_PROMISE_TG_EVENT: return 11;
    case PLPGSQL_PROMISE_TG_TAG: return 12;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_type_type(PLpgSQL_type_type value) {
  switch(value) {
    case PLPGSQL_TTYPE_SCALAR: return 1;
    case PLPGSQL_TTYPE_REC: return 2;
    case PLPGSQL_TTYPE_PSEUDO: return 3;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_stmt_type(PLpgSQL_stmt_type value) {
  switch(value) {
    case PLPGSQL_STMT_BLOCK: return 1;
    case PLPGSQL_STMT_ASSIGN: return 2;
    case PLPGSQL_STMT_IF: return 3;
    case PLPGSQL_STMT_CASE: return 4;
    case PLPGSQL_STMT_LOOP: return 5;
    case PLPGSQL_STMT_WHILE: return 6;
    case PLPGSQL_STMT_FORI: return 7;
    case PLPGSQL_STMT_FORS: return 8;
    case PLPGSQL_STMT_FORC: return 9;
    case PLPGSQL_STMT_FOREACH_A: return 10;
    case PLPGSQL_STMT_EXIT: return 11;
    case PLPGSQL_STMT_RETURN: return 12;
    case PLPGSQL_STMT_RETURN_NEXT: return 13;
    case PLPGSQL_STMT_RETURN_QUERY: return 14;
    case PLPGSQL_STMT_RAISE: return 15;
    case PLPGSQL_STMT_ASSERT: return 16;
    case PLPGSQL_STMT_EXECSQL: return 17;
    case PLPGSQL_STMT_DYNEXECUTE: return 18;
    case PLPGSQL_STMT_DYNFORS: return 19;
    case PLPGSQL_STMT_GETDIAG: return 20;
    case PLPGSQL_STMT_OPEN: return 21;
    case PLPGSQL_STMT_FETCH: return 22;
    case PLPGSQL_STMT_CLOSE: return 23;
    case PLPGSQL_STMT_PERFORM: return 24;
    case PLPGSQL_STMT_CALL: return 25;
    case PLPGSQL_STMT_COMMIT: return 26;
    case PLPGSQL_STMT_ROLLBACK: return 27;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_getdiag_kind(PLpgSQL_getdiag_kind value) {
  switch(value) {
    case PLPGSQL_GETDIAG_ROW_COUNT: return 1;
    case PLPGSQL_GETDIAG_ROUTINE_OID: return 2;
    case PLPGSQL_GETDIAG_CONTEXT: return 3;
    case PLPGSQL_GETDIAG_ERROR_CONTEXT: return 4;
    case PLPGSQL_GETDIAG_ERROR_DETAIL: return 5;
    case PLPGSQL_GETDIAG_ERROR_HINT: return 6;
    case PLPGSQL_GETDIAG_RETURNED_SQLSTATE: return 7;
    case PLPGSQL_GETDIAG_COLUMN_NAME: return 8;
    case PLPGSQL_GETDIAG_CONSTRAINT_NAME: return 9;
    case PLPGSQL_GETDIAG_DATATYPE_NAME: return 10;
    case PLPGSQL_GETDIAG_MESSAGE_TEXT: return 11;
    case PLPGSQL_GETDIAG_TABLE_NAME: return 12;
    case PLPGSQL_GETDIAG_SCHEMA_NAME: return 13;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_raise_option_type(PLpgSQL_raise_option_type value) {
  switch(value) {
    case PLPGSQL_RAISEOPTION_ERRCODE: return 1;
    case PLPGSQL_RAISEOPTION_MESSAGE: return 2;
    case PLPGSQL_RAISEOPTION_DETAIL: return 3;
    case PLPGSQL_RAISEOPTION_HINT: return 4;
    case PLPGSQL_RAISEOPTION_COLUMN: return 5;
    case PLPGSQL_RAISEOPTION_CONSTRAINT: return 6;
    case PLPGSQL_RAISEOPTION_DATATYPE: return 7;
    case PLPGSQL_RAISEOPTION_TABLE: return 8;
    case PLPGSQL_RAISEOPTION_SCHEMA: return 9;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_resolve_option(PLpgSQL_resolve_option value) {
  switch(value) {
    case PLPGSQL_RESOLVE_ERROR: return 1;
    case PLPGSQL_RESOLVE_VARIABLE: return 2;
    case PLPGSQL_RESOLVE_COLUMN: return 3;
  }
  return 0;
}

static int
_plpgsqlEnumToIntPLpgSQL_trigtype(PLpgSQL_trigtype value) {
  switch(value) {
    case PLPGSQL_DML_TRIGGER: return 1;
    case PLPGSQL_EVENT_TRIGGER: return 2;
    case PLPGSQL_NOT_TRIGGER: return 3;
  }
  return 0;
}


static PLpgSQL_nsitem_type
_plpgsqlIntToEnumPLpgSQL_nsitem_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_NSTYPE_LABEL;
    case 2: return PLPGSQL_NSTYPE_VAR;
    case 3: return PLPGSQL_NSTYPE_REC;
  }
  return PLPGSQL_NSTYPE_LABEL;
}

static PLpgSQL_label_type
_plpgsqlIntToEnumPLpgSQL_label_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_LABEL_BLOCK;
    case 2: return PLPGSQL_LABEL_LOOP;
    case 3: return PLPGSQL_LABEL_OTHER;
  }
  return PLPGSQL_LABEL_BLOCK;
}

static PLpgSQL_datum_type
_plpgsqlIntToEnumPLpgSQL_datum_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_DTYPE_VAR;
    case 2: return PLPGSQL_DTYPE_ROW;
    case 3: return PLPGSQL_DTYPE_REC;
    case 4: return PLPGSQL_DTYPE_RECFIELD;
    case 5: return PLPGSQL_DTYPE_PROMISE;
  }
  return PLPGSQL_DTYPE_VAR;
}

static PLpgSQL_promise_type
_plpgsqlIntToEnumPLpgSQL_promise_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_PROMISE_NONE;
    case 2: return PLPGSQL_PROMISE_TG_NAME;
    case 3: return PLPGSQL_PROMISE_TG_WHEN;
    case 4: return PLPGSQL_PROMISE_TG_LEVEL;
    case 5: return PLPGSQL_PROMISE_TG_OP;
    case 6: return PLPGSQL_PROMISE_TG_RELID;
    case 7: return PLPGSQL_PROMISE_TG_TABLE_NAME;
    case 8: return PLPGSQL_PROMISE_TG_TABLE_SCHEMA;
    case 9: return PLPGSQL_PROMISE_TG_NARGS;
    case 10: return PLPGSQL_PROMISE_TG_ARGV;
    case 11: return PLPGSQL_PROMISE_TG_EVENT;
    case 12: return PLPGSQL_PROMISE_TG_TAG;
  }
  return PLPGSQL_PROMISE_NONE;
}

static PLpgSQL_type_type
_plpgsqlIntToEnumPLpgSQL_type_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_TTYPE_SCALAR;
    case 2: return PLPGSQL_TTYPE_REC;
    case 3: return PLPGSQL_TTYPE_PSEUDO;
  }
  return PLPGSQL_TTYPE_SCALAR;
}

static PLpgSQL_stmt_type
_plpgsqlIntToEnumPLpgSQL_stmt_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_STMT_BLOCK;
    case 2: return PLPGSQL_STMT_ASSIGN;
    case 3: return PLPGSQL_STMT_IF;
    case 4: return PLPGSQL_STMT_CASE;
    case 5: return PLPGSQL_STMT_LOOP;
    case 6: return PLPGSQL_STMT_WHILE;
    case 7: return PLPGSQL_STMT_FORI;
    case 8: return PLPGSQL_STMT_FORS;
    case 9: return PLPGSQL_STMT_FORC;
    case 10: return PLPGSQL_STMT_FOREACH_A;
    case 11: return PLPGSQL_STMT_EXIT;
    case 12: return PLPGSQL_STMT_RETURN;
    case 13: return PLPGSQL_STMT_RETURN_NEXT;
    case 14: return PLPGSQL_STMT_RETURN_QUERY;
    case 15: return PLPGSQL_STMT_RAISE;
    case 16: return PLPGSQL_STMT_ASSERT;
    case 17: return PLPGSQL_STMT_EXECSQL;
    case 18: return PLPGSQL_STMT_DYNEXECUTE;
    case 19: return PLPGSQL_STMT_DYNFORS;
    case 20: return PLPGSQL_STMT_GETDIAG;
    case 21: return PLPGSQL_STMT_OPEN;
    case 22: return PLPGSQL_STMT_FETCH;
    case 23: return PLPGSQL_STMT_CLOSE;
    case 24: return PLPGSQL_STMT_PERFORM;
    case 25: return PLPGSQL_STMT_CALL;
    case 26: return PLPGSQL_STMT_COMMIT;
    case 27: return PLPGSQL_STMT_ROLLBACK;
  }
  return PLPGSQL_STMT_BLOCK;
}

static PLpgSQL_getdiag_kind
_plpgsqlIntToEnumPLpgSQL_getdiag_kind(int value) {
  switch(value) {
    case 1: return PLPGSQL_GETDIAG_ROW_COUNT;
    case 2: return PLPGSQL_GETDIAG_ROUTINE_OID;
    case 3: return PLPGSQL_GETDIAG_CONTEXT;
    case 4: return PLPGSQL_GETDIAG_ERROR_CONTEXT;
    case 5: return PLPGSQL_GETDIAG_ERROR_DETAIL;
    case 6: return PLPGSQL_GETDIAG_ERROR_HINT;
    case 7: return PLPGSQL_GETDIAG_RETURNED_SQLSTATE;
    case 8: return PLPGSQL_GETDIAG_COLUMN_NAME;
    case 9: return PLPGSQL_GETDIAG_CONSTRAINT_NAME;
    case 10: return PLPGSQL_GETDIAG_DATATYPE_NAME;
    case 11: return PLPGSQL_GETDIAG_MESSAGE_TEXT;
    case 12: return PLPGSQL_GETDIAG_TABLE_NAME;
    case 13: return PLPGSQL_GETDIAG_SCHEMA_NAME;
  }
  return PLPGSQL_GETDIAG_ROW_COUNT;
}

static PLpgSQL_raise_option_type
_plpgsqlIntToEnumPLpgSQL_raise_option_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_RAISEOPTION_ERRCODE;
    case 2: return PLPGSQL_RAISEOPTION_MESSAGE;
    case 3: return PLPGSQL_RAISEOPTION_DETAIL;
    case 4: return PLPGSQL_RAISEOPTION_HINT;
    case 5: return PLPGSQL_RAISEOPTION_COLUMN;
    case 6: return PLPGSQL_RAISEOPTION_CONSTRAINT;
    case 7: return PLPGSQL_RAISEOPTION_DATATYPE;
    case 8: return PLPGSQL_RAISEOPTION_TABLE;
    case 9: return PLPGSQL_RAISEOPTION_SCHEMA;
  }
  return PLPGSQL_RAISEOPTION_ERRCODE;
}

static PLpgSQL_resolve_option
_plpgsqlIntToEnumPLpgSQL_resolve_option(int value) {
  switch(value) {
    case 1: return PLPGSQL_RESOLVE_ERROR;
    case 2: return PLPGSQL_RESOLVE_VARIABLE;
    case 3: return PLPGSQL_RESOLVE_COLUMN;
  }
  return PLPGSQL_RESOLVE_ERROR;
}

static PLpgSQL_trigtype
_plpgsqlIntToEnumPLpgSQL_trigtype(int value) {
  switch(value) {
    case 1: return PLPGSQL_DML_TRIGGER;
    case 2: return PLPGSQL_EVENT_TRIGGER;
    case 3: return PLPGSQL_NOT_TRIGGER;
  }
  return PLPGSQL_DML_TRIGGER;
}

