// This file is autogenerated by ./scripts/generate_plpgsql_protobuf.rb

// Forward declarations for dispatchers (used by macros)
static void _outPLpgSQL_stmt(PgQuery__PLpgSQLStmt *out, const PLpgSQL_stmt *node);
static void _outPLpgSQL_datum(PgQuery__PLpgSQLDatum *out, const PLpgSQL_datum *node);


static void _outPLpgSQL_type(PgQuery__PLpgSQLType *out, const PLpgSQL_type *node);
static void _outPLpgSQL_expr(PgQuery__PLpgSQLExpr *out, const PLpgSQL_expr *node);
static void _outPLpgSQL_var(PgQuery__PLpgSQLVar *out, const PLpgSQL_var *node);
static void _outPLpgSQL_row(PgQuery__PLpgSQLRow *out, const PLpgSQL_row *node);
static void _outPLpgSQL_rec(PgQuery__PLpgSQLRec *out, const PLpgSQL_rec *node);
static void _outPLpgSQL_recfield(PgQuery__PLpgSQLRecfield *out, const PLpgSQL_recfield *node);
static void _outPLpgSQL_condition(PgQuery__PLpgSQLCondition *out, const PLpgSQL_condition *node);
static void _outPLpgSQL_exception_block(PgQuery__PLpgSQLExceptionBlock *out, const PLpgSQL_exception_block *node);
static void _outPLpgSQL_exception(PgQuery__PLpgSQLException *out, const PLpgSQL_exception *node);
static void _outPLpgSQL_stmt_block(PgQuery__PLpgSQLStmtBlock *out, const PLpgSQL_stmt_block *node);
static void _outPLpgSQL_stmt_assign(PgQuery__PLpgSQLStmtAssign *out, const PLpgSQL_stmt_assign *node);
static void _outPLpgSQL_stmt_perform(PgQuery__PLpgSQLStmtPerform *out, const PLpgSQL_stmt_perform *node);
static void _outPLpgSQL_stmt_call(PgQuery__PLpgSQLStmtCall *out, const PLpgSQL_stmt_call *node);
static void _outPLpgSQL_stmt_commit(PgQuery__PLpgSQLStmtCommit *out, const PLpgSQL_stmt_commit *node);
static void _outPLpgSQL_stmt_rollback(PgQuery__PLpgSQLStmtRollback *out, const PLpgSQL_stmt_rollback *node);
static void _outPLpgSQL_diag_item(PgQuery__PLpgSQLDiagItem *out, const PLpgSQL_diag_item *node);
static void _outPLpgSQL_stmt_getdiag(PgQuery__PLpgSQLStmtGetdiag *out, const PLpgSQL_stmt_getdiag *node);
static void _outPLpgSQL_stmt_if(PgQuery__PLpgSQLStmtIf *out, const PLpgSQL_stmt_if *node);
static void _outPLpgSQL_if_elsif(PgQuery__PLpgSQLIfElsif *out, const PLpgSQL_if_elsif *node);
static void _outPLpgSQL_stmt_case(PgQuery__PLpgSQLStmtCase *out, const PLpgSQL_stmt_case *node);
static void _outPLpgSQL_case_when(PgQuery__PLpgSQLCaseWhen *out, const PLpgSQL_case_when *node);
static void _outPLpgSQL_stmt_loop(PgQuery__PLpgSQLStmtLoop *out, const PLpgSQL_stmt_loop *node);
static void _outPLpgSQL_stmt_while(PgQuery__PLpgSQLStmtWhile *out, const PLpgSQL_stmt_while *node);
static void _outPLpgSQL_stmt_fori(PgQuery__PLpgSQLStmtFori *out, const PLpgSQL_stmt_fori *node);
static void _outPLpgSQL_stmt_fors(PgQuery__PLpgSQLStmtFors *out, const PLpgSQL_stmt_fors *node);
static void _outPLpgSQL_stmt_forc(PgQuery__PLpgSQLStmtForc *out, const PLpgSQL_stmt_forc *node);
static void _outPLpgSQL_stmt_dynfors(PgQuery__PLpgSQLStmtDynfors *out, const PLpgSQL_stmt_dynfors *node);
static void _outPLpgSQL_stmt_foreach_a(PgQuery__PLpgSQLStmtForeachA *out, const PLpgSQL_stmt_foreach_a *node);
static void _outPLpgSQL_stmt_open(PgQuery__PLpgSQLStmtOpen *out, const PLpgSQL_stmt_open *node);
static void _outPLpgSQL_stmt_fetch(PgQuery__PLpgSQLStmtFetch *out, const PLpgSQL_stmt_fetch *node);
static void _outPLpgSQL_stmt_close(PgQuery__PLpgSQLStmtClose *out, const PLpgSQL_stmt_close *node);
static void _outPLpgSQL_stmt_exit(PgQuery__PLpgSQLStmtExit *out, const PLpgSQL_stmt_exit *node);
static void _outPLpgSQL_stmt_return(PgQuery__PLpgSQLStmtReturn *out, const PLpgSQL_stmt_return *node);
static void _outPLpgSQL_stmt_return_next(PgQuery__PLpgSQLStmtReturnNext *out, const PLpgSQL_stmt_return_next *node);
static void _outPLpgSQL_stmt_return_query(PgQuery__PLpgSQLStmtReturnQuery *out, const PLpgSQL_stmt_return_query *node);
static void _outPLpgSQL_stmt_raise(PgQuery__PLpgSQLStmtRaise *out, const PLpgSQL_stmt_raise *node);
static void _outPLpgSQL_raise_option(PgQuery__PLpgSQLRaiseOption *out, const PLpgSQL_raise_option *node);
static void _outPLpgSQL_stmt_assert(PgQuery__PLpgSQLStmtAssert *out, const PLpgSQL_stmt_assert *node);
static void _outPLpgSQL_stmt_execsql(PgQuery__PLpgSQLStmtExecsql *out, const PLpgSQL_stmt_execsql *node);
static void _outPLpgSQL_stmt_dynexecute(PgQuery__PLpgSQLStmtDynexecute *out, const PLpgSQL_stmt_dynexecute *node);
static void _outPLpgSQL_function(PgQuery__PLpgSQLFunction *out, const PLpgSQL_function *node);


static void
_outPLpgSQL_stmt(PgQuery__PLpgSQLStmt *out, const PLpgSQL_stmt *node)
{
  switch (node->cmd_type) {
    case PLPGSQL_STMT_BLOCK:
      out->stmt_block = palloc0(sizeof(PgQuery__PLpgSQLStmtBlock));
      pg_query__plpg_sql_stmt_block__init(out->stmt_block);
      _outPLpgSQL_stmt_block(out->stmt_block, (const PLpgSQL_stmt_block *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_BLOCK;
      break;
    case PLPGSQL_STMT_ASSIGN:
      out->stmt_assign = palloc0(sizeof(PgQuery__PLpgSQLStmtAssign));
      pg_query__plpg_sql_stmt_assign__init(out->stmt_assign);
      _outPLpgSQL_stmt_assign(out->stmt_assign, (const PLpgSQL_stmt_assign *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_ASSIGN;
      break;
    case PLPGSQL_STMT_IF:
      out->stmt_if = palloc0(sizeof(PgQuery__PLpgSQLStmtIf));
      pg_query__plpg_sql_stmt_if__init(out->stmt_if);
      _outPLpgSQL_stmt_if(out->stmt_if, (const PLpgSQL_stmt_if *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_IF;
      break;
    case PLPGSQL_STMT_CASE:
      out->stmt_case_ = palloc0(sizeof(PgQuery__PLpgSQLStmtCase));
      pg_query__plpg_sql_stmt_case__init(out->stmt_case_);
      _outPLpgSQL_stmt_case(out->stmt_case_, (const PLpgSQL_stmt_case *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_CASE_;
      break;
    case PLPGSQL_STMT_LOOP:
      out->stmt_loop = palloc0(sizeof(PgQuery__PLpgSQLStmtLoop));
      pg_query__plpg_sql_stmt_loop__init(out->stmt_loop);
      _outPLpgSQL_stmt_loop(out->stmt_loop, (const PLpgSQL_stmt_loop *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_LOOP;
      break;
    case PLPGSQL_STMT_WHILE:
      out->stmt_while = palloc0(sizeof(PgQuery__PLpgSQLStmtWhile));
      pg_query__plpg_sql_stmt_while__init(out->stmt_while);
      _outPLpgSQL_stmt_while(out->stmt_while, (const PLpgSQL_stmt_while *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_WHILE;
      break;
    case PLPGSQL_STMT_FORI:
      out->stmt_fori = palloc0(sizeof(PgQuery__PLpgSQLStmtFori));
      pg_query__plpg_sql_stmt_fori__init(out->stmt_fori);
      _outPLpgSQL_stmt_fori(out->stmt_fori, (const PLpgSQL_stmt_fori *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FORI;
      break;
    case PLPGSQL_STMT_FORS:
      out->stmt_fors = palloc0(sizeof(PgQuery__PLpgSQLStmtFors));
      pg_query__plpg_sql_stmt_fors__init(out->stmt_fors);
      _outPLpgSQL_stmt_fors(out->stmt_fors, (const PLpgSQL_stmt_fors *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FORS;
      break;
    case PLPGSQL_STMT_FORC:
      out->stmt_forc = palloc0(sizeof(PgQuery__PLpgSQLStmtForc));
      pg_query__plpg_sql_stmt_forc__init(out->stmt_forc);
      _outPLpgSQL_stmt_forc(out->stmt_forc, (const PLpgSQL_stmt_forc *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FORC;
      break;
    case PLPGSQL_STMT_FOREACH_A:
      out->stmt_foreach_a = palloc0(sizeof(PgQuery__PLpgSQLStmtForeachA));
      pg_query__plpg_sql_stmt_foreach_a__init(out->stmt_foreach_a);
      _outPLpgSQL_stmt_foreach_a(out->stmt_foreach_a, (const PLpgSQL_stmt_foreach_a *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FOREACH_A;
      break;
    case PLPGSQL_STMT_EXIT:
      out->stmt_exit = palloc0(sizeof(PgQuery__PLpgSQLStmtExit));
      pg_query__plpg_sql_stmt_exit__init(out->stmt_exit);
      _outPLpgSQL_stmt_exit(out->stmt_exit, (const PLpgSQL_stmt_exit *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_EXIT;
      break;
    case PLPGSQL_STMT_RETURN:
      out->stmt_return = palloc0(sizeof(PgQuery__PLpgSQLStmtReturn));
      pg_query__plpg_sql_stmt_return__init(out->stmt_return);
      _outPLpgSQL_stmt_return(out->stmt_return, (const PLpgSQL_stmt_return *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RETURN;
      break;
    case PLPGSQL_STMT_RETURN_NEXT:
      out->stmt_return_next = palloc0(sizeof(PgQuery__PLpgSQLStmtReturnNext));
      pg_query__plpg_sql_stmt_return_next__init(out->stmt_return_next);
      _outPLpgSQL_stmt_return_next(out->stmt_return_next, (const PLpgSQL_stmt_return_next *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RETURN_NEXT;
      break;
    case PLPGSQL_STMT_RETURN_QUERY:
      out->stmt_return_query = palloc0(sizeof(PgQuery__PLpgSQLStmtReturnQuery));
      pg_query__plpg_sql_stmt_return_query__init(out->stmt_return_query);
      _outPLpgSQL_stmt_return_query(out->stmt_return_query, (const PLpgSQL_stmt_return_query *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RETURN_QUERY;
      break;
    case PLPGSQL_STMT_RAISE:
      out->stmt_raise = palloc0(sizeof(PgQuery__PLpgSQLStmtRaise));
      pg_query__plpg_sql_stmt_raise__init(out->stmt_raise);
      _outPLpgSQL_stmt_raise(out->stmt_raise, (const PLpgSQL_stmt_raise *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RAISE;
      break;
    case PLPGSQL_STMT_ASSERT:
      out->stmt_assert = palloc0(sizeof(PgQuery__PLpgSQLStmtAssert));
      pg_query__plpg_sql_stmt_assert__init(out->stmt_assert);
      _outPLpgSQL_stmt_assert(out->stmt_assert, (const PLpgSQL_stmt_assert *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_ASSERT;
      break;
    case PLPGSQL_STMT_EXECSQL:
      out->stmt_execsql = palloc0(sizeof(PgQuery__PLpgSQLStmtExecsql));
      pg_query__plpg_sql_stmt_execsql__init(out->stmt_execsql);
      _outPLpgSQL_stmt_execsql(out->stmt_execsql, (const PLpgSQL_stmt_execsql *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_EXECSQL;
      break;
    case PLPGSQL_STMT_DYNEXECUTE:
      out->stmt_dynexecute = palloc0(sizeof(PgQuery__PLpgSQLStmtDynexecute));
      pg_query__plpg_sql_stmt_dynexecute__init(out->stmt_dynexecute);
      _outPLpgSQL_stmt_dynexecute(out->stmt_dynexecute, (const PLpgSQL_stmt_dynexecute *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_DYNEXECUTE;
      break;
    case PLPGSQL_STMT_DYNFORS:
      out->stmt_dynfors = palloc0(sizeof(PgQuery__PLpgSQLStmtDynfors));
      pg_query__plpg_sql_stmt_dynfors__init(out->stmt_dynfors);
      _outPLpgSQL_stmt_dynfors(out->stmt_dynfors, (const PLpgSQL_stmt_dynfors *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_DYNFORS;
      break;
    case PLPGSQL_STMT_GETDIAG:
      out->stmt_getdiag = palloc0(sizeof(PgQuery__PLpgSQLStmtGetdiag));
      pg_query__plpg_sql_stmt_getdiag__init(out->stmt_getdiag);
      _outPLpgSQL_stmt_getdiag(out->stmt_getdiag, (const PLpgSQL_stmt_getdiag *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_GETDIAG;
      break;
    case PLPGSQL_STMT_OPEN:
      out->stmt_open = palloc0(sizeof(PgQuery__PLpgSQLStmtOpen));
      pg_query__plpg_sql_stmt_open__init(out->stmt_open);
      _outPLpgSQL_stmt_open(out->stmt_open, (const PLpgSQL_stmt_open *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_OPEN;
      break;
    case PLPGSQL_STMT_FETCH:
      out->stmt_fetch = palloc0(sizeof(PgQuery__PLpgSQLStmtFetch));
      pg_query__plpg_sql_stmt_fetch__init(out->stmt_fetch);
      _outPLpgSQL_stmt_fetch(out->stmt_fetch, (const PLpgSQL_stmt_fetch *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FETCH;
      break;
    case PLPGSQL_STMT_CLOSE:
      out->stmt_close = palloc0(sizeof(PgQuery__PLpgSQLStmtClose));
      pg_query__plpg_sql_stmt_close__init(out->stmt_close);
      _outPLpgSQL_stmt_close(out->stmt_close, (const PLpgSQL_stmt_close *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_CLOSE;
      break;
    case PLPGSQL_STMT_PERFORM:
      out->stmt_perform = palloc0(sizeof(PgQuery__PLpgSQLStmtPerform));
      pg_query__plpg_sql_stmt_perform__init(out->stmt_perform);
      _outPLpgSQL_stmt_perform(out->stmt_perform, (const PLpgSQL_stmt_perform *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_PERFORM;
      break;
    case PLPGSQL_STMT_CALL:
      out->stmt_call = palloc0(sizeof(PgQuery__PLpgSQLStmtCall));
      pg_query__plpg_sql_stmt_call__init(out->stmt_call);
      _outPLpgSQL_stmt_call(out->stmt_call, (const PLpgSQL_stmt_call *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_CALL;
      break;
    case PLPGSQL_STMT_COMMIT:
      out->stmt_commit = palloc0(sizeof(PgQuery__PLpgSQLStmtCommit));
      pg_query__plpg_sql_stmt_commit__init(out->stmt_commit);
      _outPLpgSQL_stmt_commit(out->stmt_commit, (const PLpgSQL_stmt_commit *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_COMMIT;
      break;
    case PLPGSQL_STMT_ROLLBACK:
      out->stmt_rollback = palloc0(sizeof(PgQuery__PLpgSQLStmtRollback));
      pg_query__plpg_sql_stmt_rollback__init(out->stmt_rollback);
      _outPLpgSQL_stmt_rollback(out->stmt_rollback, (const PLpgSQL_stmt_rollback *) node);
      out->stmt_case = PG_QUERY__PLPG_SQL_STMT__STMT_STMT_ROLLBACK;
      break;
  }
}



static void
_outPLpgSQL_datum(PgQuery__PLpgSQLDatum *out, const PLpgSQL_datum *node)
{
  switch (node->dtype) {
    case PLPGSQL_DTYPE_VAR:
      out->var = palloc0(sizeof(PgQuery__PLpgSQLVar));
      pg_query__plpg_sql_var__init(out->var);
      _outPLpgSQL_var(out->var, (const PLpgSQL_var *) node);
      out->datum_case = PG_QUERY__PLPG_SQL_DATUM__DATUM_VAR;
      break;
    case PLPGSQL_DTYPE_PROMISE:
      out->var = palloc0(sizeof(PgQuery__PLpgSQLVar));
      pg_query__plpg_sql_var__init(out->var);
      _outPLpgSQL_var(out->var, (const PLpgSQL_var *) node);
      out->datum_case = PG_QUERY__PLPG_SQL_DATUM__DATUM_VAR;
      break;
    case PLPGSQL_DTYPE_ROW:
      out->row = palloc0(sizeof(PgQuery__PLpgSQLRow));
      pg_query__plpg_sql_row__init(out->row);
      _outPLpgSQL_row(out->row, (const PLpgSQL_row *) node);
      out->datum_case = PG_QUERY__PLPG_SQL_DATUM__DATUM_ROW;
      break;
    case PLPGSQL_DTYPE_REC:
      out->rec = palloc0(sizeof(PgQuery__PLpgSQLRec));
      pg_query__plpg_sql_rec__init(out->rec);
      _outPLpgSQL_rec(out->rec, (const PLpgSQL_rec *) node);
      out->datum_case = PG_QUERY__PLPG_SQL_DATUM__DATUM_REC;
      break;
    case PLPGSQL_DTYPE_RECFIELD:
      out->recfield = palloc0(sizeof(PgQuery__PLpgSQLRecfield));
      pg_query__plpg_sql_recfield__init(out->recfield);
      _outPLpgSQL_recfield(out->recfield, (const PLpgSQL_recfield *) node);
      out->datum_case = PG_QUERY__PLPG_SQL_DATUM__DATUM_RECFIELD;
      break;
  }
}



static void
_outPLpgSQL_type(PgQuery__PLpgSQLType *out, const PLpgSQL_type *node)
{
  WRITE_STRING_FIELD(typname, typname, typname);
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_type_type, ttype, ttype);
}

static void
_outPLpgSQL_expr(PgQuery__PLpgSQLExpr *out, const PLpgSQL_expr *node)
{
  WRITE_STRING_FIELD(query, query, query);
  WRITE_INT_FIELD(parse_mode, parseMode, parseMode);
}

static void
_outPLpgSQL_var(PgQuery__PLpgSQLVar *out, const PLpgSQL_var *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  WRITE_INT_FIELD(dno, dno, dno);
  WRITE_STRING_FIELD(refname, refname, refname);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(isconst, isconst, isconst);
  WRITE_BOOL_FIELD(notnull, notnull, notnull);
  WRITE_PLPGSQL_EXPR_FIELD(default_val, default_val);
  WRITE_PLPGSQL_TYPE_FIELD(datatype, datatype);
  WRITE_PLPGSQL_EXPR_FIELD(cursor_explicit_expr, cursor_explicit_expr);
  WRITE_INT_FIELD(cursor_explicit_argrow, cursor_explicit_argrow, cursor_explicit_argrow);
  WRITE_INT_FIELD(cursor_options, cursor_options, cursor_options);
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_promise_type, promise, promise);
}

static void
_outPLpgSQL_row(PgQuery__PLpgSQLRow *out, const PLpgSQL_row *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  WRITE_INT_FIELD(dno, dno, dno);
  WRITE_STRING_FIELD(refname, refname, refname);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(isconst, isconst, isconst);
  WRITE_BOOL_FIELD(notnull, notnull, notnull);
  WRITE_PLPGSQL_EXPR_FIELD(default_val, default_val);
  WRITE_INT_FIELD(nfields, nfields, nfields);
}

static void
_outPLpgSQL_rec(PgQuery__PLpgSQLRec *out, const PLpgSQL_rec *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  WRITE_INT_FIELD(dno, dno, dno);
  WRITE_STRING_FIELD(refname, refname, refname);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(isconst, isconst, isconst);
  WRITE_BOOL_FIELD(notnull, notnull, notnull);
  WRITE_PLPGSQL_EXPR_FIELD(default_val, default_val);
  WRITE_PLPGSQL_TYPE_FIELD(datatype, datatype);
  WRITE_INT_FIELD(firstfield, firstfield, firstfield);
}

static void
_outPLpgSQL_recfield(PgQuery__PLpgSQLRecfield *out, const PLpgSQL_recfield *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  WRITE_INT_FIELD(dno, dno, dno);
  WRITE_STRING_FIELD(fieldname, fieldname, fieldname);
  WRITE_INT_FIELD(recparentno, recparentno, recparentno);
  WRITE_INT_FIELD(nextfield, nextfield, nextfield);
}

static void
_outPLpgSQL_condition(PgQuery__PLpgSQLCondition *out, const PLpgSQL_condition *node)
{
  WRITE_INT_FIELD(sqlerrstate, sqlerrstate, sqlerrstate);
  WRITE_STRING_FIELD(condname, condname, condname);
}

static void
_outPLpgSQL_exception_block(PgQuery__PLpgSQLExceptionBlock *out, const PLpgSQL_exception_block *node)
{
  WRITE_INT_FIELD(sqlstate_varno, sqlstate_varno, sqlstate_varno);
  WRITE_INT_FIELD(sqlerrm_varno, sqlerrm_varno, sqlerrm_varno);
  WRITE_PLPGSQL_EXCEPTION_LIST_FIELD(exc_list, exc_list);
}

static void
_outPLpgSQL_exception(PgQuery__PLpgSQLException *out, const PLpgSQL_exception *node)
{
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_CONDITION_FIELD(conditions, conditions);
  WRITE_PLPGSQL_STMT_LIST_FIELD(action, action);
}

static void
_outPLpgSQL_stmt_block(PgQuery__PLpgSQLStmtBlock *out, const PLpgSQL_stmt_block *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
  WRITE_INT_FIELD(n_initvars, n_initvars, n_initvars);
  WRITE_PLPGSQL_EXCEPTION_BLOCK_FIELD(exceptions, exceptions);
}

static void
_outPLpgSQL_stmt_assign(PgQuery__PLpgSQLStmtAssign *out, const PLpgSQL_stmt_assign *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_INT_FIELD(varno, varno, varno);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
}

static void
_outPLpgSQL_stmt_perform(PgQuery__PLpgSQLStmtPerform *out, const PLpgSQL_stmt_perform *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
}

static void
_outPLpgSQL_stmt_call(PgQuery__PLpgSQLStmtCall *out, const PLpgSQL_stmt_call *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
  WRITE_BOOL_FIELD(is_call, is_call, is_call);
  WRITE_PLPGSQL_DATUM_FIELD(target, target);
}

static void
_outPLpgSQL_stmt_commit(PgQuery__PLpgSQLStmtCommit *out, const PLpgSQL_stmt_commit *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(chain, chain, chain);
}

static void
_outPLpgSQL_stmt_rollback(PgQuery__PLpgSQLStmtRollback *out, const PLpgSQL_stmt_rollback *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(chain, chain, chain);
}

static void
_outPLpgSQL_diag_item(PgQuery__PLpgSQLDiagItem *out, const PLpgSQL_diag_item *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_getdiag_kind, kind, kind);
  WRITE_INT_FIELD(target, target, target);
}

static void
_outPLpgSQL_stmt_getdiag(PgQuery__PLpgSQLStmtGetdiag *out, const PLpgSQL_stmt_getdiag *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(is_stacked, is_stacked, is_stacked);
  WRITE_PLPGSQL_DIAG_ITEM_LIST_FIELD(diag_items, diag_items);
}

static void
_outPLpgSQL_stmt_if(PgQuery__PLpgSQLStmtIf *out, const PLpgSQL_stmt_if *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(cond, cond);
  WRITE_PLPGSQL_STMT_LIST_FIELD(then_body, then_body);
  WRITE_PLPGSQL_IF_ELSIF_LIST_FIELD(elsif_list, elsif_list);
  WRITE_PLPGSQL_STMT_LIST_FIELD(else_body, else_body);
}

static void
_outPLpgSQL_if_elsif(PgQuery__PLpgSQLIfElsif *out, const PLpgSQL_if_elsif *node)
{
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(cond, cond);
  WRITE_PLPGSQL_STMT_LIST_FIELD(stmts, stmts);
}

static void
_outPLpgSQL_stmt_case(PgQuery__PLpgSQLStmtCase *out, const PLpgSQL_stmt_case *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(t_expr, t_expr);
  WRITE_INT_FIELD(t_varno, t_varno, t_varno);
  WRITE_PLPGSQL_CASE_WHEN_LIST_FIELD(case_when_list, case_when_list);
  WRITE_BOOL_FIELD(have_else, have_else, have_else);
  WRITE_PLPGSQL_STMT_LIST_FIELD(else_stmts, else_stmts);
}

static void
_outPLpgSQL_case_when(PgQuery__PLpgSQLCaseWhen *out, const PLpgSQL_case_when *node)
{
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
  WRITE_PLPGSQL_STMT_LIST_FIELD(stmts, stmts);
}

static void
_outPLpgSQL_stmt_loop(PgQuery__PLpgSQLStmtLoop *out, const PLpgSQL_stmt_loop *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
}

static void
_outPLpgSQL_stmt_while(PgQuery__PLpgSQLStmtWhile *out, const PLpgSQL_stmt_while *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_EXPR_FIELD(cond, cond);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
}

static void
_outPLpgSQL_stmt_fori(PgQuery__PLpgSQLStmtFori *out, const PLpgSQL_stmt_fori *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_VAR_FIELD(var, var);
  WRITE_PLPGSQL_EXPR_FIELD(lower, lower);
  WRITE_PLPGSQL_EXPR_FIELD(upper, upper);
  WRITE_PLPGSQL_EXPR_FIELD(step, step);
  WRITE_INT_FIELD(reverse, reverse, reverse);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
}

static void
_outPLpgSQL_stmt_fors(PgQuery__PLpgSQLStmtFors *out, const PLpgSQL_stmt_fors *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_DATUM_FIELD(var, var);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
  WRITE_PLPGSQL_EXPR_FIELD(query, query);
}

static void
_outPLpgSQL_stmt_forc(PgQuery__PLpgSQLStmtForc *out, const PLpgSQL_stmt_forc *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_DATUM_FIELD(var, var);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
  WRITE_INT_FIELD(curvar, curvar, curvar);
  WRITE_PLPGSQL_EXPR_FIELD(argquery, argquery);
}

static void
_outPLpgSQL_stmt_dynfors(PgQuery__PLpgSQLStmtDynfors *out, const PLpgSQL_stmt_dynfors *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_DATUM_FIELD(var, var);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
  WRITE_PLPGSQL_EXPR_FIELD(query, query);
  WRITE_PLPGSQL_EXPR_LIST_FIELD(params, params);
}

static void
_outPLpgSQL_stmt_foreach_a(PgQuery__PLpgSQLStmtForeachA *out, const PLpgSQL_stmt_foreach_a *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_INT_FIELD(varno, varno, varno);
  WRITE_INT_FIELD(slice, slice, slice);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
  WRITE_PLPGSQL_STMT_LIST_FIELD(body, body);
}

static void
_outPLpgSQL_stmt_open(PgQuery__PLpgSQLStmtOpen *out, const PLpgSQL_stmt_open *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_INT_FIELD(curvar, curvar, curvar);
  WRITE_INT_FIELD(cursor_options, cursor_options, cursor_options);
  WRITE_PLPGSQL_EXPR_FIELD(argquery, argquery);
  WRITE_PLPGSQL_EXPR_FIELD(query, query);
  WRITE_PLPGSQL_EXPR_FIELD(dynquery, dynquery);
  WRITE_PLPGSQL_EXPR_LIST_FIELD(params, params);
}

static void
_outPLpgSQL_stmt_fetch(PgQuery__PLpgSQLStmtFetch *out, const PLpgSQL_stmt_fetch *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_DATUM_FIELD(target, target);
  WRITE_INT_FIELD(curvar, curvar, curvar);
  WRITE_INT_FIELD(direction, direction, direction);
  WRITE_LONG_FIELD(how_many, how_many, how_many);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
  WRITE_BOOL_FIELD(is_move, is_move, is_move);
  WRITE_BOOL_FIELD(returns_multiple_rows, returns_multiple_rows, returns_multiple_rows);
}

static void
_outPLpgSQL_stmt_close(PgQuery__PLpgSQLStmtClose *out, const PLpgSQL_stmt_close *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_INT_FIELD(curvar, curvar, curvar);
}

static void
_outPLpgSQL_stmt_exit(PgQuery__PLpgSQLStmtExit *out, const PLpgSQL_stmt_exit *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_BOOL_FIELD(is_exit, is_exit, is_exit);
  WRITE_STRING_FIELD(label, label, label);
  WRITE_PLPGSQL_EXPR_FIELD(cond, cond);
}

static void
_outPLpgSQL_stmt_return(PgQuery__PLpgSQLStmtReturn *out, const PLpgSQL_stmt_return *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
  WRITE_INT_FIELD(retvarno, retvarno, retvarno);
}

static void
_outPLpgSQL_stmt_return_next(PgQuery__PLpgSQLStmtReturnNext *out, const PLpgSQL_stmt_return_next *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
  WRITE_INT_FIELD(retvarno, retvarno, retvarno);
}

static void
_outPLpgSQL_stmt_return_query(PgQuery__PLpgSQLStmtReturnQuery *out, const PLpgSQL_stmt_return_query *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(query, query);
  WRITE_PLPGSQL_EXPR_FIELD(dynquery, dynquery);
  WRITE_PLPGSQL_EXPR_LIST_FIELD(params, params);
}

static void
_outPLpgSQL_stmt_raise(PgQuery__PLpgSQLStmtRaise *out, const PLpgSQL_stmt_raise *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_INT_FIELD(elog_level, elog_level, elog_level);
  WRITE_STRING_FIELD(condname, condname, condname);
  WRITE_STRING_FIELD(message, message, message);
  WRITE_PLPGSQL_EXPR_LIST_FIELD(params, params);
  WRITE_PLPGSQL_RAISE_OPTION_LIST_FIELD(options, options);
}

static void
_outPLpgSQL_raise_option(PgQuery__PLpgSQLRaiseOption *out, const PLpgSQL_raise_option *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_raise_option_type, opt_type, opt_type);
  WRITE_PLPGSQL_EXPR_FIELD(expr, expr);
}

static void
_outPLpgSQL_stmt_assert(PgQuery__PLpgSQLStmtAssert *out, const PLpgSQL_stmt_assert *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(cond, cond);
  WRITE_PLPGSQL_EXPR_FIELD(message, message);
}

static void
_outPLpgSQL_stmt_execsql(PgQuery__PLpgSQLStmtExecsql *out, const PLpgSQL_stmt_execsql *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(sqlstmt, sqlstmt);
  WRITE_BOOL_FIELD(mod_stmt, mod_stmt, mod_stmt);
  WRITE_BOOL_FIELD(mod_stmt_set, mod_stmt_set, mod_stmt_set);
  WRITE_BOOL_FIELD(into, into, into);
  WRITE_BOOL_FIELD(strict, strict, strict);
  WRITE_PLPGSQL_DATUM_FIELD(target, target);
}

static void
_outPLpgSQL_stmt_dynexecute(PgQuery__PLpgSQLStmtDynexecute *out, const PLpgSQL_stmt_dynexecute *node)
{
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  WRITE_INT_FIELD(lineno, lineno, lineno);
  WRITE_PLPGSQL_EXPR_FIELD(query, query);
  WRITE_BOOL_FIELD(into, into, into);
  WRITE_BOOL_FIELD(strict, strict, strict);
  WRITE_PLPGSQL_DATUM_FIELD(target, target);
  WRITE_PLPGSQL_EXPR_LIST_FIELD(params, params);
}

static void
_outPLpgSQL_function(PgQuery__PLpgSQLFunction *out, const PLpgSQL_function *node)
{
  WRITE_STRING_FIELD(fn_signature, fn_signature, fn_signature);
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_trigtype, fn_is_trigger, fn_is_trigger);
  WRITE_INT_FIELD(out_param_varno, out_param_varno, out_param_varno);
  WRITE_INT_FIELD(found_varno, found_varno, found_varno);
  WRITE_INT_FIELD(new_varno, new_varno, new_varno);
  WRITE_INT_FIELD(old_varno, old_varno, old_varno);
  WRITE_PLPGSQL_ENUM_FIELD(PLpgSQL_resolve_option, resolve_option, resolve_option);
  WRITE_BOOL_FIELD(print_strict_params, print_strict_params, print_strict_params);
  WRITE_INT_FIELD(extra_warnings, extra_warnings, extra_warnings);
  WRITE_INT_FIELD(extra_errors, extra_errors, extra_errors);
  WRITE_INT_FIELD(ndatums, ndatums, ndatums);
  WRITE_PLPGSQL_STMT_BLOCK_FIELD(action, action);
}


