// This file is autogenerated by ./scripts/generate_node_support.sh

static const char*
_enumToStringPLpgSQL_promise_type(PLpgSQL_promise_type value) {
  switch(value) {
    case PLPGSQL_PROMISE_NONE: return "PLPGSQL_PROMISE_NONE";
    case PLPGSQL_PROMISE_TG_NAME: return "PLPGSQL_PROMISE_TG_NAME";
    case PLPGSQL_PROMISE_TG_WHEN: return "PLPGSQL_PROMISE_TG_WHEN";
    case PLPGSQL_PROMISE_TG_LEVEL: return "PLPGSQL_PROMISE_TG_LEVEL";
    case PLPGSQL_PROMISE_TG_OP: return "PLPGSQL_PROMISE_TG_OP";
    case PLPGSQL_PROMISE_TG_RELID: return "PLPGSQL_PROMISE_TG_RELID";
    case PLPGSQL_PROMISE_TG_TABLE_NAME: return "PLPGSQL_PROMISE_TG_TABLE_NAME";
    case PLPGSQL_PROMISE_TG_TABLE_SCHEMA: return "PLPGSQL_PROMISE_TG_TABLE_SCHEMA";
    case PLPGSQL_PROMISE_TG_NARGS: return "PLPGSQL_PROMISE_TG_NARGS";
    case PLPGSQL_PROMISE_TG_ARGV: return "PLPGSQL_PROMISE_TG_ARGV";
    case PLPGSQL_PROMISE_TG_EVENT: return "PLPGSQL_PROMISE_TG_EVENT";
    case PLPGSQL_PROMISE_TG_TAG: return "PLPGSQL_PROMISE_TG_TAG";
  }
  Assert(false);
  return NULL;
}

static const char*
_enumToStringPLpgSQL_type_type(PLpgSQL_type_type value) {
  switch(value) {
    case PLPGSQL_TTYPE_SCALAR: return "PLPGSQL_TTYPE_SCALAR";
    case PLPGSQL_TTYPE_REC: return "PLPGSQL_TTYPE_REC";
    case PLPGSQL_TTYPE_PSEUDO: return "PLPGSQL_TTYPE_PSEUDO";
  }
  Assert(false);
  return NULL;
}

static const char*
_enumToStringPLpgSQL_getdiag_kind(PLpgSQL_getdiag_kind value) {
  switch(value) {
    case PLPGSQL_GETDIAG_ROW_COUNT: return "PLPGSQL_GETDIAG_ROW_COUNT";
    case PLPGSQL_GETDIAG_ROUTINE_OID: return "PLPGSQL_GETDIAG_ROUTINE_OID";
    case PLPGSQL_GETDIAG_CONTEXT: return "PLPGSQL_GETDIAG_CONTEXT";
    case PLPGSQL_GETDIAG_ERROR_CONTEXT: return "PLPGSQL_GETDIAG_ERROR_CONTEXT";
    case PLPGSQL_GETDIAG_ERROR_DETAIL: return "PLPGSQL_GETDIAG_ERROR_DETAIL";
    case PLPGSQL_GETDIAG_ERROR_HINT: return "PLPGSQL_GETDIAG_ERROR_HINT";
    case PLPGSQL_GETDIAG_RETURNED_SQLSTATE: return "PLPGSQL_GETDIAG_RETURNED_SQLSTATE";
    case PLPGSQL_GETDIAG_COLUMN_NAME: return "PLPGSQL_GETDIAG_COLUMN_NAME";
    case PLPGSQL_GETDIAG_CONSTRAINT_NAME: return "PLPGSQL_GETDIAG_CONSTRAINT_NAME";
    case PLPGSQL_GETDIAG_DATATYPE_NAME: return "PLPGSQL_GETDIAG_DATATYPE_NAME";
    case PLPGSQL_GETDIAG_MESSAGE_TEXT: return "PLPGSQL_GETDIAG_MESSAGE_TEXT";
    case PLPGSQL_GETDIAG_TABLE_NAME: return "PLPGSQL_GETDIAG_TABLE_NAME";
    case PLPGSQL_GETDIAG_SCHEMA_NAME: return "PLPGSQL_GETDIAG_SCHEMA_NAME";
  }
  Assert(false);
  return NULL;
}

static const char*
_enumToStringPLpgSQL_raise_option_type(PLpgSQL_raise_option_type value) {
  switch(value) {
    case PLPGSQL_RAISEOPTION_ERRCODE: return "PLPGSQL_RAISEOPTION_ERRCODE";
    case PLPGSQL_RAISEOPTION_MESSAGE: return "PLPGSQL_RAISEOPTION_MESSAGE";
    case PLPGSQL_RAISEOPTION_DETAIL: return "PLPGSQL_RAISEOPTION_DETAIL";
    case PLPGSQL_RAISEOPTION_HINT: return "PLPGSQL_RAISEOPTION_HINT";
    case PLPGSQL_RAISEOPTION_COLUMN: return "PLPGSQL_RAISEOPTION_COLUMN";
    case PLPGSQL_RAISEOPTION_CONSTRAINT: return "PLPGSQL_RAISEOPTION_CONSTRAINT";
    case PLPGSQL_RAISEOPTION_DATATYPE: return "PLPGSQL_RAISEOPTION_DATATYPE";
    case PLPGSQL_RAISEOPTION_TABLE: return "PLPGSQL_RAISEOPTION_TABLE";
    case PLPGSQL_RAISEOPTION_SCHEMA: return "PLPGSQL_RAISEOPTION_SCHEMA";
  }
  Assert(false);
  return NULL;
}

static const char*
_enumToStringPLpgSQL_resolve_option(PLpgSQL_resolve_option value) {
  switch(value) {
    case PLPGSQL_RESOLVE_ERROR: return "PLPGSQL_RESOLVE_ERROR";
    case PLPGSQL_RESOLVE_VARIABLE: return "PLPGSQL_RESOLVE_VARIABLE";
    case PLPGSQL_RESOLVE_COLUMN: return "PLPGSQL_RESOLVE_COLUMN";
  }
  Assert(false);
  return NULL;
}

static const char*
_enumToStringPLpgSQL_trigtype(PLpgSQL_trigtype value) {
  switch(value) {
    case PLPGSQL_DML_TRIGGER: return "PLPGSQL_DML_TRIGGER";
    case PLPGSQL_EVENT_TRIGGER: return "PLPGSQL_EVENT_TRIGGER";
    case PLPGSQL_NOT_TRIGGER: return "PLPGSQL_NOT_TRIGGER";
  }
  Assert(false);
  return NULL;
}

static int
_enumToIntPLpgSQL_promise_type(PLpgSQL_promise_type value) {
  switch(value) {
    case PLPGSQL_PROMISE_NONE: return 1;
    case PLPGSQL_PROMISE_TG_NAME: return 2;
    case PLPGSQL_PROMISE_TG_WHEN: return 3;
    case PLPGSQL_PROMISE_TG_LEVEL: return 4;
    case PLPGSQL_PROMISE_TG_OP: return 5;
    case PLPGSQL_PROMISE_TG_RELID: return 6;
    case PLPGSQL_PROMISE_TG_TABLE_NAME: return 7;
    case PLPGSQL_PROMISE_TG_TABLE_SCHEMA: return 8;
    case PLPGSQL_PROMISE_TG_NARGS: return 9;
    case PLPGSQL_PROMISE_TG_ARGV: return 10;
    case PLPGSQL_PROMISE_TG_EVENT: return 11;
    case PLPGSQL_PROMISE_TG_TAG: return 12;
  }
  Assert(false);
  return -1;
}

static int
_enumToIntPLpgSQL_type_type(PLpgSQL_type_type value) {
  switch(value) {
    case PLPGSQL_TTYPE_SCALAR: return 1;
    case PLPGSQL_TTYPE_REC: return 2;
    case PLPGSQL_TTYPE_PSEUDO: return 3;
  }
  Assert(false);
  return -1;
}

static int
_enumToIntPLpgSQL_getdiag_kind(PLpgSQL_getdiag_kind value) {
  switch(value) {
    case PLPGSQL_GETDIAG_ROW_COUNT: return 1;
    case PLPGSQL_GETDIAG_ROUTINE_OID: return 2;
    case PLPGSQL_GETDIAG_CONTEXT: return 3;
    case PLPGSQL_GETDIAG_ERROR_CONTEXT: return 4;
    case PLPGSQL_GETDIAG_ERROR_DETAIL: return 5;
    case PLPGSQL_GETDIAG_ERROR_HINT: return 6;
    case PLPGSQL_GETDIAG_RETURNED_SQLSTATE: return 7;
    case PLPGSQL_GETDIAG_COLUMN_NAME: return 8;
    case PLPGSQL_GETDIAG_CONSTRAINT_NAME: return 9;
    case PLPGSQL_GETDIAG_DATATYPE_NAME: return 10;
    case PLPGSQL_GETDIAG_MESSAGE_TEXT: return 11;
    case PLPGSQL_GETDIAG_TABLE_NAME: return 12;
    case PLPGSQL_GETDIAG_SCHEMA_NAME: return 13;
  }
  Assert(false);
  return -1;
}

static int
_enumToIntPLpgSQL_raise_option_type(PLpgSQL_raise_option_type value) {
  switch(value) {
    case PLPGSQL_RAISEOPTION_ERRCODE: return 1;
    case PLPGSQL_RAISEOPTION_MESSAGE: return 2;
    case PLPGSQL_RAISEOPTION_DETAIL: return 3;
    case PLPGSQL_RAISEOPTION_HINT: return 4;
    case PLPGSQL_RAISEOPTION_COLUMN: return 5;
    case PLPGSQL_RAISEOPTION_CONSTRAINT: return 6;
    case PLPGSQL_RAISEOPTION_DATATYPE: return 7;
    case PLPGSQL_RAISEOPTION_TABLE: return 8;
    case PLPGSQL_RAISEOPTION_SCHEMA: return 9;
  }
  Assert(false);
  return -1;
}

static int
_enumToIntPLpgSQL_resolve_option(PLpgSQL_resolve_option value) {
  switch(value) {
    case PLPGSQL_RESOLVE_ERROR: return 1;
    case PLPGSQL_RESOLVE_VARIABLE: return 2;
    case PLPGSQL_RESOLVE_COLUMN: return 3;
  }
  Assert(false);
  return -1;
}

static int
_enumToIntPLpgSQL_trigtype(PLpgSQL_trigtype value) {
  switch(value) {
    case PLPGSQL_DML_TRIGGER: return 1;
    case PLPGSQL_EVENT_TRIGGER: return 2;
    case PLPGSQL_NOT_TRIGGER: return 3;
  }
  Assert(false);
  return -1;
}

static PLpgSQL_promise_type
_intToEnumPLpgSQL_promise_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_PROMISE_NONE;
    case 2: return PLPGSQL_PROMISE_TG_NAME;
    case 3: return PLPGSQL_PROMISE_TG_WHEN;
    case 4: return PLPGSQL_PROMISE_TG_LEVEL;
    case 5: return PLPGSQL_PROMISE_TG_OP;
    case 6: return PLPGSQL_PROMISE_TG_RELID;
    case 7: return PLPGSQL_PROMISE_TG_TABLE_NAME;
    case 8: return PLPGSQL_PROMISE_TG_TABLE_SCHEMA;
    case 9: return PLPGSQL_PROMISE_TG_NARGS;
    case 10: return PLPGSQL_PROMISE_TG_ARGV;
    case 11: return PLPGSQL_PROMISE_TG_EVENT;
    case 12: return PLPGSQL_PROMISE_TG_TAG;
  }
  Assert(false);
  return PLPGSQL_PROMISE_NONE;
}

static PLpgSQL_type_type
_intToEnumPLpgSQL_type_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_TTYPE_SCALAR;
    case 2: return PLPGSQL_TTYPE_REC;
    case 3: return PLPGSQL_TTYPE_PSEUDO;
  }
  Assert(false);
  return PLPGSQL_TTYPE_SCALAR;
}

static PLpgSQL_getdiag_kind
_intToEnumPLpgSQL_getdiag_kind(int value) {
  switch(value) {
    case 1: return PLPGSQL_GETDIAG_ROW_COUNT;
    case 2: return PLPGSQL_GETDIAG_ROUTINE_OID;
    case 3: return PLPGSQL_GETDIAG_CONTEXT;
    case 4: return PLPGSQL_GETDIAG_ERROR_CONTEXT;
    case 5: return PLPGSQL_GETDIAG_ERROR_DETAIL;
    case 6: return PLPGSQL_GETDIAG_ERROR_HINT;
    case 7: return PLPGSQL_GETDIAG_RETURNED_SQLSTATE;
    case 8: return PLPGSQL_GETDIAG_COLUMN_NAME;
    case 9: return PLPGSQL_GETDIAG_CONSTRAINT_NAME;
    case 10: return PLPGSQL_GETDIAG_DATATYPE_NAME;
    case 11: return PLPGSQL_GETDIAG_MESSAGE_TEXT;
    case 12: return PLPGSQL_GETDIAG_TABLE_NAME;
    case 13: return PLPGSQL_GETDIAG_SCHEMA_NAME;
  }
  Assert(false);
  return PLPGSQL_GETDIAG_ROW_COUNT;
}

static PLpgSQL_raise_option_type
_intToEnumPLpgSQL_raise_option_type(int value) {
  switch(value) {
    case 1: return PLPGSQL_RAISEOPTION_ERRCODE;
    case 2: return PLPGSQL_RAISEOPTION_MESSAGE;
    case 3: return PLPGSQL_RAISEOPTION_DETAIL;
    case 4: return PLPGSQL_RAISEOPTION_HINT;
    case 5: return PLPGSQL_RAISEOPTION_COLUMN;
    case 6: return PLPGSQL_RAISEOPTION_CONSTRAINT;
    case 7: return PLPGSQL_RAISEOPTION_DATATYPE;
    case 8: return PLPGSQL_RAISEOPTION_TABLE;
    case 9: return PLPGSQL_RAISEOPTION_SCHEMA;
  }
  Assert(false);
  return PLPGSQL_RAISEOPTION_ERRCODE;
}

static PLpgSQL_resolve_option
_intToEnumPLpgSQL_resolve_option(int value) {
  switch(value) {
    case 1: return PLPGSQL_RESOLVE_ERROR;
    case 2: return PLPGSQL_RESOLVE_VARIABLE;
    case 3: return PLPGSQL_RESOLVE_COLUMN;
  }
  Assert(false);
  return PLPGSQL_RESOLVE_ERROR;
}

static PLpgSQL_trigtype
_intToEnumPLpgSQL_trigtype(int value) {
  switch(value) {
    case 1: return PLPGSQL_DML_TRIGGER;
    case 2: return PLPGSQL_EVENT_TRIGGER;
    case 3: return PLPGSQL_NOT_TRIGGER;
  }
  Assert(false);
  return PLPGSQL_DML_TRIGGER;
}

static void _outPLpgSQL_function(OUT_TYPE(PLpgSQL_function, PLpgSQL_function) out_node, const PLpgSQL_function *node);
static void _outPLpgSQL_datum(OUT_TYPE(PLpgSQL_datum, PLpgSQL_datum) out_node, const PLpgSQL_datum *node);
static void _outPLpgSQL_stmt_block(OUT_TYPE(PLpgSQL_stmt_block, PLpgSQL_stmt_block) out_node, const PLpgSQL_stmt_block *node);
static void _outPLpgSQL_var(OUT_TYPE(PLpgSQL_var, PLpgSQL_var) out_node, const PLpgSQL_var *node);
static void _outPLpgSQL_row(OUT_TYPE(PLpgSQL_row, PLpgSQL_row) out_node, const PLpgSQL_row *node);
static void _outPLpgSQL_rec(OUT_TYPE(PLpgSQL_rec, PLpgSQL_rec) out_node, const PLpgSQL_rec *node);
static void _outPLpgSQL_recfield(OUT_TYPE(PLpgSQL_recfield, PLpgSQL_recfield) out_node, const PLpgSQL_recfield *node);
static void _outPLpgSQL_stmt(OUT_TYPE(PLpgSQL_stmt, PLpgSQL_stmt) out_node, const PLpgSQL_stmt *node);
static void _outPLpgSQL_exception_block(OUT_TYPE(PLpgSQL_exception_block, PLpgSQL_exception_block) out_node, const PLpgSQL_exception_block *node);
static void _outPLpgSQL_expr(OUT_TYPE(PLpgSQL_expr, PLpgSQL_expr) out_node, const PLpgSQL_expr *node);
static void _outPLpgSQL_type(OUT_TYPE(PLpgSQL_type, PLpgSQL_type) out_node, const PLpgSQL_type *node);
static void _outPLpgSQL_stmt_assign(OUT_TYPE(PLpgSQL_stmt_assign, PLpgSQL_stmt_assign) out_node, const PLpgSQL_stmt_assign *node);
static void _outPLpgSQL_stmt_if(OUT_TYPE(PLpgSQL_stmt_if, PLpgSQL_stmt_if) out_node, const PLpgSQL_stmt_if *node);
static void _outPLpgSQL_stmt_case(OUT_TYPE(PLpgSQL_stmt_case, PLpgSQL_stmt_case) out_node, const PLpgSQL_stmt_case *node);
static void _outPLpgSQL_stmt_loop(OUT_TYPE(PLpgSQL_stmt_loop, PLpgSQL_stmt_loop) out_node, const PLpgSQL_stmt_loop *node);
static void _outPLpgSQL_stmt_while(OUT_TYPE(PLpgSQL_stmt_while, PLpgSQL_stmt_while) out_node, const PLpgSQL_stmt_while *node);
static void _outPLpgSQL_stmt_fori(OUT_TYPE(PLpgSQL_stmt_fori, PLpgSQL_stmt_fori) out_node, const PLpgSQL_stmt_fori *node);
static void _outPLpgSQL_stmt_fors(OUT_TYPE(PLpgSQL_stmt_fors, PLpgSQL_stmt_fors) out_node, const PLpgSQL_stmt_fors *node);
static void _outPLpgSQL_stmt_forc(OUT_TYPE(PLpgSQL_stmt_forc, PLpgSQL_stmt_forc) out_node, const PLpgSQL_stmt_forc *node);
static void _outPLpgSQL_stmt_foreach_a(OUT_TYPE(PLpgSQL_stmt_foreach_a, PLpgSQL_stmt_foreach_a) out_node, const PLpgSQL_stmt_foreach_a *node);
static void _outPLpgSQL_stmt_exit(OUT_TYPE(PLpgSQL_stmt_exit, PLpgSQL_stmt_exit) out_node, const PLpgSQL_stmt_exit *node);
static void _outPLpgSQL_stmt_return(OUT_TYPE(PLpgSQL_stmt_return, PLpgSQL_stmt_return) out_node, const PLpgSQL_stmt_return *node);
static void _outPLpgSQL_stmt_return_next(OUT_TYPE(PLpgSQL_stmt_return_next, PLpgSQL_stmt_return_next) out_node, const PLpgSQL_stmt_return_next *node);
static void _outPLpgSQL_stmt_return_query(OUT_TYPE(PLpgSQL_stmt_return_query, PLpgSQL_stmt_return_query) out_node, const PLpgSQL_stmt_return_query *node);
static void _outPLpgSQL_stmt_raise(OUT_TYPE(PLpgSQL_stmt_raise, PLpgSQL_stmt_raise) out_node, const PLpgSQL_stmt_raise *node);
static void _outPLpgSQL_stmt_assert(OUT_TYPE(PLpgSQL_stmt_assert, PLpgSQL_stmt_assert) out_node, const PLpgSQL_stmt_assert *node);
static void _outPLpgSQL_stmt_execsql(OUT_TYPE(PLpgSQL_stmt_execsql, PLpgSQL_stmt_execsql) out_node, const PLpgSQL_stmt_execsql *node);
static void _outPLpgSQL_stmt_dynexecute(OUT_TYPE(PLpgSQL_stmt_dynexecute, PLpgSQL_stmt_dynexecute) out_node, const PLpgSQL_stmt_dynexecute *node);
static void _outPLpgSQL_stmt_dynfors(OUT_TYPE(PLpgSQL_stmt_dynfors, PLpgSQL_stmt_dynfors) out_node, const PLpgSQL_stmt_dynfors *node);
static void _outPLpgSQL_stmt_getdiag(OUT_TYPE(PLpgSQL_stmt_getdiag, PLpgSQL_stmt_getdiag) out_node, const PLpgSQL_stmt_getdiag *node);
static void _outPLpgSQL_stmt_open(OUT_TYPE(PLpgSQL_stmt_open, PLpgSQL_stmt_open) out_node, const PLpgSQL_stmt_open *node);
static void _outPLpgSQL_stmt_fetch(OUT_TYPE(PLpgSQL_stmt_fetch, PLpgSQL_stmt_fetch) out_node, const PLpgSQL_stmt_fetch *node);
static void _outPLpgSQL_stmt_close(OUT_TYPE(PLpgSQL_stmt_close, PLpgSQL_stmt_close) out_node, const PLpgSQL_stmt_close *node);
static void _outPLpgSQL_stmt_perform(OUT_TYPE(PLpgSQL_stmt_perform, PLpgSQL_stmt_perform) out_node, const PLpgSQL_stmt_perform *node);
static void _outPLpgSQL_stmt_call(OUT_TYPE(PLpgSQL_stmt_call, PLpgSQL_stmt_call) out_node, const PLpgSQL_stmt_call *node);
static void _outPLpgSQL_stmt_commit(OUT_TYPE(PLpgSQL_stmt_commit, PLpgSQL_stmt_commit) out_node, const PLpgSQL_stmt_commit *node);
static void _outPLpgSQL_stmt_rollback(OUT_TYPE(PLpgSQL_stmt_rollback, PLpgSQL_stmt_rollback) out_node, const PLpgSQL_stmt_rollback *node);
static void _outPLpgSQL_exception(OUT_TYPE(PLpgSQL_exception, PLpgSQL_exception) out_node, const PLpgSQL_exception *node);
static void _outPLpgSQL_if_elsif(OUT_TYPE(PLpgSQL_if_elsif, PLpgSQL_if_elsif) out_node, const PLpgSQL_if_elsif *node);
static void _outPLpgSQL_case_when(OUT_TYPE(PLpgSQL_case_when, PLpgSQL_case_when) out_node, const PLpgSQL_case_when *node);
static void _outPLpgSQL_raise_option(OUT_TYPE(PLpgSQL_raise_option, PLpgSQL_raise_option) out_node, const PLpgSQL_raise_option *node);
static void _outPLpgSQL_diag_item(OUT_TYPE(PLpgSQL_diag_item, PLpgSQL_diag_item) out_node, const PLpgSQL_diag_item *node);
static void _outPLpgSQL_condition(OUT_TYPE(PLpgSQL_condition, PLpgSQL_condition) out_node, const PLpgSQL_condition *node);


static void
_outPLpgSQL_function(OUT_TYPE(PLpgSQL_function, PLpgSQL_function) out, const PLpgSQL_function *node)
{
  WRITE_STRING_FIELD(PLpgSQL_function, fn_signature, fn_signature, fn_signature);
  WRITE_UINT_FIELD(PLpgSQL_function, fn_oid, fn_oid, fn_oid);
  WRITE_ENUM_FIELD(PLpgSQL_function, PLpgSQL_trigtype, fn_is_trigger, fn_is_trigger, fn_is_trigger);
  WRITE_UINT_FIELD(PLpgSQL_function, fn_input_collation, fn_input_collation, fn_input_collation);
  WRITE_UINT_FIELD(PLpgSQL_function, fn_rettype, fn_rettype, fn_rettype);
  WRITE_INT_FIELD(PLpgSQL_function, fn_rettyplen, fn_rettyplen, fn_rettyplen);
  WRITE_BOOL_FIELD(PLpgSQL_function, fn_retistuple, fn_retistuple, fn_retistuple);
  WRITE_BOOL_FIELD(PLpgSQL_function, fn_retisdomain, fn_retisdomain, fn_retisdomain);
  WRITE_BOOL_FIELD(PLpgSQL_function, fn_retset, fn_retset, fn_retset);
  WRITE_BOOL_FIELD(PLpgSQL_function, fn_readonly, fn_readonly, fn_readonly);
  WRITE_CHAR_FIELD(PLpgSQL_function, fn_prokind, fn_prokind, fn_prokind);
  WRITE_PLPGSQL_INT_ARRAY_FIELD(PLpgSQL_function, fn_argvarnos, fn_argvarnos, fn_argvarnos, fn_nargs);
  WRITE_INT_FIELD(PLpgSQL_function, out_param_varno, out_param_varno, out_param_varno);
  WRITE_INT_FIELD(PLpgSQL_function, found_varno, found_varno, found_varno);
  WRITE_INT_FIELD(PLpgSQL_function, new_varno, new_varno, new_varno);
  WRITE_INT_FIELD(PLpgSQL_function, old_varno, old_varno, old_varno);
  WRITE_ENUM_FIELD(PLpgSQL_function, PLpgSQL_resolve_option, resolve_option, resolve_option, resolve_option);
  WRITE_BOOL_FIELD(PLpgSQL_function, print_strict_params, print_strict_params, print_strict_params);
  WRITE_INT_FIELD(PLpgSQL_function, extra_warnings, extra_warnings, extra_warnings);
  WRITE_INT_FIELD(PLpgSQL_function, extra_errors, extra_errors, extra_errors);
  WRITE_PLPGSQL_PTR_ARRAY_FIELD(PLpgSQL_function, PLpgSQL_datum, datums, datums, datums, ndatums);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_function, PLpgSQL_stmt_block, p__lpg_sql_stmt_block, action, action, action);
  WRITE_UINT_FIELD(PLpgSQL_function, nstatements, nstatements, nstatements);
  WRITE_BOOL_FIELD(PLpgSQL_function, requires_procedure_resowner, requires_procedure_resowner, requires_procedure_resowner);
  WRITE_BOOL_FIELD(PLpgSQL_function, has_exception_block, has_exception_block, has_exception_block);
}

static void
_outPLpgSQL_datum(OUT_TYPE(PLpgSQL_datum, PLpgSQL_datum) out, const PLpgSQL_datum *node)
{
  check_stack_depth();

  switch (node->dtype)
  {
    case PLPGSQL_DTYPE_VAR:
    case PLPGSQL_DTYPE_PROMISE:
      OUT_PLPGSQL_NODE(PLpgSQL_datum, PLpgSQL_var, var);
      break;
    case PLPGSQL_DTYPE_ROW:
      OUT_PLPGSQL_NODE(PLpgSQL_datum, PLpgSQL_row, row);
      break;
    case PLPGSQL_DTYPE_REC:
      OUT_PLPGSQL_NODE(PLpgSQL_datum, PLpgSQL_rec, rec);
      break;
    case PLPGSQL_DTYPE_RECFIELD:
      OUT_PLPGSQL_NODE(PLpgSQL_datum, PLpgSQL_recfield, recfield);
      break;
    default:
      elog(ERROR, "unrecognized PLpgSQL_datum_type: %d", (int) node->dtype);
  }
}

static void
_outPLpgSQL_stmt_block(OUT_TYPE(PLpgSQL_stmt_block, PLpgSQL_stmt_block) out, const PLpgSQL_stmt_block *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_block, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_block, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_block, label, label, label);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_block, PLpgSQL_stmt, body, body, body);
  WRITE_PLPGSQL_INT_ARRAY_FIELD(PLpgSQL_stmt_block, initvarnos, initvarnos, initvarnos, n_initvars);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_block, PLpgSQL_exception_block, p__lpg_sql_exception_block, exceptions, exceptions, exceptions);
}

static void
_outPLpgSQL_var(OUT_TYPE(PLpgSQL_var, PLpgSQL_var) out, const PLpgSQL_var *node)
{
  WRITE_INT_FIELD(PLpgSQL_var, dno, dno, dno);
  WRITE_STRING_FIELD(PLpgSQL_var, refname, refname, refname);
  WRITE_INT_FIELD(PLpgSQL_var, lineno, lineno, lineno);
  WRITE_BOOL_FIELD(PLpgSQL_var, isconst, isconst, isconst);
  WRITE_BOOL_FIELD(PLpgSQL_var, notnull, notnull, notnull);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_var, PLpgSQL_expr, p__lpg_sql_expr, default_val, default_val, default_val);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_var, PLpgSQL_type, p__lpg_sql_type, datatype, datatype, datatype);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_var, PLpgSQL_expr, p__lpg_sql_expr, cursor_explicit_expr, cursor_explicit_expr, cursor_explicit_expr);
  WRITE_INT_FIELD(PLpgSQL_var, cursor_explicit_argrow, cursor_explicit_argrow, cursor_explicit_argrow);
  WRITE_INT_FIELD(PLpgSQL_var, cursor_options, cursor_options, cursor_options);
  WRITE_ENUM_FIELD(PLpgSQL_var, PLpgSQL_promise_type, promise, promise, promise);
}

static void
_outPLpgSQL_row(OUT_TYPE(PLpgSQL_row, PLpgSQL_row) out, const PLpgSQL_row *node)
{
  WRITE_INT_FIELD(PLpgSQL_row, dno, dno, dno);
  WRITE_STRING_FIELD(PLpgSQL_row, refname, refname, refname);
  WRITE_INT_FIELD(PLpgSQL_row, lineno, lineno, lineno);
  WRITE_BOOL_FIELD(PLpgSQL_row, isconst, isconst, isconst);
  WRITE_BOOL_FIELD(PLpgSQL_row, notnull, notnull, notnull);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_row, PLpgSQL_expr, p__lpg_sql_expr, default_val, default_val, default_val);
  WRITE_PLPGSQL_CUSTOM_FIELD(PLpgSQL_row, fields, fields, fieldnames);
}

static void
_outPLpgSQL_rec(OUT_TYPE(PLpgSQL_rec, PLpgSQL_rec) out, const PLpgSQL_rec *node)
{
  WRITE_INT_FIELD(PLpgSQL_rec, dno, dno, dno);
  WRITE_STRING_FIELD(PLpgSQL_rec, refname, refname, refname);
  WRITE_INT_FIELD(PLpgSQL_rec, lineno, lineno, lineno);
  WRITE_BOOL_FIELD(PLpgSQL_rec, isconst, isconst, isconst);
  WRITE_BOOL_FIELD(PLpgSQL_rec, notnull, notnull, notnull);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_rec, PLpgSQL_expr, p__lpg_sql_expr, default_val, default_val, default_val);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_rec, PLpgSQL_type, p__lpg_sql_type, datatype, datatype, datatype);
  WRITE_UINT_FIELD(PLpgSQL_rec, rectypeid, rectypeid, rectypeid);
  WRITE_INT_FIELD(PLpgSQL_rec, firstfield, firstfield, firstfield);
}

static void
_outPLpgSQL_recfield(OUT_TYPE(PLpgSQL_recfield, PLpgSQL_recfield) out, const PLpgSQL_recfield *node)
{
  WRITE_INT_FIELD(PLpgSQL_recfield, dno, dno, dno);
  WRITE_STRING_FIELD(PLpgSQL_recfield, fieldname, fieldname, fieldname);
  WRITE_INT_FIELD(PLpgSQL_recfield, recparentno, recparentno, recparentno);
  WRITE_INT_FIELD(PLpgSQL_recfield, nextfield, nextfield, nextfield);
}

static void
_outPLpgSQL_stmt(OUT_TYPE(PLpgSQL_stmt, PLpgSQL_stmt) out, const PLpgSQL_stmt *node)
{
  check_stack_depth();

  switch (node->cmd_type)
  {
    case PLPGSQL_STMT_BLOCK:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_block, stmt_block);
      break;
    case PLPGSQL_STMT_ASSIGN:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_assign, stmt_assign);
      break;
    case PLPGSQL_STMT_IF:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_if, stmt_if);
      break;
    case PLPGSQL_STMT_CASE:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_case, stmt_case);
      break;
    case PLPGSQL_STMT_LOOP:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_loop, stmt_loop);
      break;
    case PLPGSQL_STMT_WHILE:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_while, stmt_while);
      break;
    case PLPGSQL_STMT_FORI:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_fori, stmt_fori);
      break;
    case PLPGSQL_STMT_FORS:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_fors, stmt_fors);
      break;
    case PLPGSQL_STMT_FORC:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_forc, stmt_forc);
      break;
    case PLPGSQL_STMT_FOREACH_A:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_foreach_a, stmt_foreach_a);
      break;
    case PLPGSQL_STMT_EXIT:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_exit, stmt_exit);
      break;
    case PLPGSQL_STMT_RETURN:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_return, stmt_return);
      break;
    case PLPGSQL_STMT_RETURN_NEXT:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_return_next, stmt_return_next);
      break;
    case PLPGSQL_STMT_RETURN_QUERY:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_return_query, stmt_return_query);
      break;
    case PLPGSQL_STMT_RAISE:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_raise, stmt_raise);
      break;
    case PLPGSQL_STMT_ASSERT:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_assert, stmt_assert);
      break;
    case PLPGSQL_STMT_EXECSQL:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_execsql, stmt_execsql);
      break;
    case PLPGSQL_STMT_DYNEXECUTE:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_dynexecute, stmt_dynexecute);
      break;
    case PLPGSQL_STMT_DYNFORS:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_dynfors, stmt_dynfors);
      break;
    case PLPGSQL_STMT_GETDIAG:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_getdiag, stmt_getdiag);
      break;
    case PLPGSQL_STMT_OPEN:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_open, stmt_open);
      break;
    case PLPGSQL_STMT_FETCH:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_fetch, stmt_fetch);
      break;
    case PLPGSQL_STMT_CLOSE:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_close, stmt_close);
      break;
    case PLPGSQL_STMT_PERFORM:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_perform, stmt_perform);
      break;
    case PLPGSQL_STMT_CALL:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_call, stmt_call);
      break;
    case PLPGSQL_STMT_COMMIT:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_commit, stmt_commit);
      break;
    case PLPGSQL_STMT_ROLLBACK:
      OUT_PLPGSQL_NODE(PLpgSQL_stmt, PLpgSQL_stmt_rollback, stmt_rollback);
      break;
    default:
      elog(ERROR, "unrecognized PLpgSQL_stmt_type: %d", (int) node->cmd_type);
  }
}

static void
_outPLpgSQL_exception_block(OUT_TYPE(PLpgSQL_exception_block, PLpgSQL_exception_block) out, const PLpgSQL_exception_block *node)
{
  WRITE_INT_FIELD(PLpgSQL_exception_block, sqlstate_varno, sqlstate_varno, sqlstate_varno);
  WRITE_INT_FIELD(PLpgSQL_exception_block, sqlerrm_varno, sqlerrm_varno, sqlerrm_varno);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_exception_block, PLpgSQL_exception, exc_list, exc_list, exc_list);
}

static void
_outPLpgSQL_expr(OUT_TYPE(PLpgSQL_expr, PLpgSQL_expr) out, const PLpgSQL_expr *node)
{
  WRITE_STRING_FIELD(PLpgSQL_expr, query, query, query);
  WRITE_INT_FIELD(PLpgSQL_expr, parse_mode, parseMode, parseMode);
  WRITE_INT_FIELD(PLpgSQL_expr, target_param, target_param, target_param);
  WRITE_BOOL_FIELD(PLpgSQL_expr, target_is_local, target_is_local, target_is_local);
}

static void
_outPLpgSQL_type(OUT_TYPE(PLpgSQL_type, PLpgSQL_type) out, const PLpgSQL_type *node)
{
  WRITE_STRING_FIELD(PLpgSQL_type, typname, typname, typname);
  WRITE_UINT_FIELD(PLpgSQL_type, typoid, typoid, typoid);
  WRITE_ENUM_FIELD(PLpgSQL_type, PLpgSQL_type_type, ttype, ttype, ttype);
  WRITE_INT_FIELD(PLpgSQL_type, typlen, typlen, typlen);
  WRITE_CHAR_FIELD(PLpgSQL_type, typtype, typtype, typtype);
  WRITE_UINT_FIELD(PLpgSQL_type, collation, collation, collation);
  WRITE_BOOL_FIELD(PLpgSQL_type, typisarray, typisarray, typisarray);
  WRITE_INT_FIELD(PLpgSQL_type, atttypmod, atttypmod, atttypmod);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_type, TypeName, type_name, origtypname, origtypname, origtypname);
}

static void
_outPLpgSQL_stmt_assign(OUT_TYPE(PLpgSQL_stmt_assign, PLpgSQL_stmt_assign) out, const PLpgSQL_stmt_assign *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_assign, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_assign, stmtid, stmtid, stmtid);
  WRITE_INT_FIELD(PLpgSQL_stmt_assign, varno, varno, varno);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_assign, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
}

static void
_outPLpgSQL_stmt_if(OUT_TYPE(PLpgSQL_stmt_if, PLpgSQL_stmt_if) out, const PLpgSQL_stmt_if *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_if, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_if, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_if, PLpgSQL_expr, p__lpg_sql_expr, cond, cond, cond);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_if, PLpgSQL_stmt, then_body, then_body, then_body);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_if, PLpgSQL_if_elsif, elsif_list, elsif_list, elsif_list);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_if, PLpgSQL_stmt, else_body, else_body, else_body);
}

static void
_outPLpgSQL_stmt_case(OUT_TYPE(PLpgSQL_stmt_case, PLpgSQL_stmt_case) out, const PLpgSQL_stmt_case *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_case, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_case, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_case, PLpgSQL_expr, p__lpg_sql_expr, t_expr, t_expr, t_expr);
  WRITE_INT_FIELD(PLpgSQL_stmt_case, t_varno, t_varno, t_varno);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_case, PLpgSQL_case_when, case_when_list, case_when_list, case_when_list);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_case, have_else, have_else, have_else);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_case, PLpgSQL_stmt, else_stmts, else_stmts, else_stmts);
}

static void
_outPLpgSQL_stmt_loop(OUT_TYPE(PLpgSQL_stmt_loop, PLpgSQL_stmt_loop) out, const PLpgSQL_stmt_loop *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_loop, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_loop, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_loop, label, label, label);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_loop, PLpgSQL_stmt, body, body, body);
}

static void
_outPLpgSQL_stmt_while(OUT_TYPE(PLpgSQL_stmt_while, PLpgSQL_stmt_while) out, const PLpgSQL_stmt_while *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_while, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_while, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_while, label, label, label);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_while, PLpgSQL_expr, p__lpg_sql_expr, cond, cond, cond);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_while, PLpgSQL_stmt, body, body, body);
}

static void
_outPLpgSQL_stmt_fori(OUT_TYPE(PLpgSQL_stmt_fori, PLpgSQL_stmt_fori) out, const PLpgSQL_stmt_fori *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_fori, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_fori, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_fori, label, label, label);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_fori, var_dno, var_dno, var);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_fori, PLpgSQL_expr, p__lpg_sql_expr, lower, lower, lower);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_fori, PLpgSQL_expr, p__lpg_sql_expr, upper, upper, upper);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_fori, PLpgSQL_expr, p__lpg_sql_expr, step, step, step);
  WRITE_INT_FIELD(PLpgSQL_stmt_fori, reverse, reverse, reverse);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_fori, PLpgSQL_stmt, body, body, body);
}

static void
_outPLpgSQL_stmt_fors(OUT_TYPE(PLpgSQL_stmt_fors, PLpgSQL_stmt_fors) out, const PLpgSQL_stmt_fors *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_fors, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_fors, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_fors, label, label, label);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_fors, var_dno, var_dno, var);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_fors, PLpgSQL_stmt, body, body, body);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_fors, PLpgSQL_expr, p__lpg_sql_expr, query, query, query);
}

static void
_outPLpgSQL_stmt_forc(OUT_TYPE(PLpgSQL_stmt_forc, PLpgSQL_stmt_forc) out, const PLpgSQL_stmt_forc *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_forc, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_forc, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_forc, label, label, label);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_forc, var_dno, var_dno, var);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_forc, PLpgSQL_stmt, body, body, body);
  WRITE_INT_FIELD(PLpgSQL_stmt_forc, curvar, curvar, curvar);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_forc, PLpgSQL_expr, p__lpg_sql_expr, argquery, argquery, argquery);
}

static void
_outPLpgSQL_stmt_foreach_a(OUT_TYPE(PLpgSQL_stmt_foreach_a, PLpgSQL_stmt_foreach_a) out, const PLpgSQL_stmt_foreach_a *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_foreach_a, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_foreach_a, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_foreach_a, label, label, label);
  WRITE_INT_FIELD(PLpgSQL_stmt_foreach_a, varno, varno, varno);
  WRITE_INT_FIELD(PLpgSQL_stmt_foreach_a, slice, slice, slice);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_foreach_a, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_foreach_a, PLpgSQL_stmt, body, body, body);
}

static void
_outPLpgSQL_stmt_exit(OUT_TYPE(PLpgSQL_stmt_exit, PLpgSQL_stmt_exit) out, const PLpgSQL_stmt_exit *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_exit, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_exit, stmtid, stmtid, stmtid);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_exit, is_exit, is_exit, is_exit);
  WRITE_STRING_FIELD(PLpgSQL_stmt_exit, label, label, label);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_exit, PLpgSQL_expr, p__lpg_sql_expr, cond, cond, cond);
}

static void
_outPLpgSQL_stmt_return(OUT_TYPE(PLpgSQL_stmt_return, PLpgSQL_stmt_return) out, const PLpgSQL_stmt_return *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_return, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_return, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_return, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
  WRITE_INT_FIELD(PLpgSQL_stmt_return, retvarno, retvarno, retvarno);
}

static void
_outPLpgSQL_stmt_return_next(OUT_TYPE(PLpgSQL_stmt_return_next, PLpgSQL_stmt_return_next) out, const PLpgSQL_stmt_return_next *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_return_next, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_return_next, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_return_next, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
  WRITE_INT_FIELD(PLpgSQL_stmt_return_next, retvarno, retvarno, retvarno);
}

static void
_outPLpgSQL_stmt_return_query(OUT_TYPE(PLpgSQL_stmt_return_query, PLpgSQL_stmt_return_query) out, const PLpgSQL_stmt_return_query *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_return_query, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_return_query, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_return_query, PLpgSQL_expr, p__lpg_sql_expr, query, query, query);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_return_query, PLpgSQL_expr, p__lpg_sql_expr, dynquery, dynquery, dynquery);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_return_query, PLpgSQL_expr, params, params, params);
}

static void
_outPLpgSQL_stmt_raise(OUT_TYPE(PLpgSQL_stmt_raise, PLpgSQL_stmt_raise) out, const PLpgSQL_stmt_raise *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_raise, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_raise, stmtid, stmtid, stmtid);
  WRITE_INT_FIELD(PLpgSQL_stmt_raise, elog_level, elog_level, elog_level);
  WRITE_STRING_FIELD(PLpgSQL_stmt_raise, condname, condname, condname);
  WRITE_STRING_FIELD(PLpgSQL_stmt_raise, message, message, message);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_raise, PLpgSQL_expr, params, params, params);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_raise, PLpgSQL_raise_option, options, options, options);
}

static void
_outPLpgSQL_stmt_assert(OUT_TYPE(PLpgSQL_stmt_assert, PLpgSQL_stmt_assert) out, const PLpgSQL_stmt_assert *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_assert, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_assert, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_assert, PLpgSQL_expr, p__lpg_sql_expr, cond, cond, cond);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_assert, PLpgSQL_expr, p__lpg_sql_expr, message, message, message);
}

static void
_outPLpgSQL_stmt_execsql(OUT_TYPE(PLpgSQL_stmt_execsql, PLpgSQL_stmt_execsql) out, const PLpgSQL_stmt_execsql *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_execsql, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_execsql, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_execsql, PLpgSQL_expr, p__lpg_sql_expr, sqlstmt, sqlstmt, sqlstmt);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_execsql, into, into, into);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_execsql, strict, strict, strict);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_execsql, target_dno, target_dno, target);
}

static void
_outPLpgSQL_stmt_dynexecute(OUT_TYPE(PLpgSQL_stmt_dynexecute, PLpgSQL_stmt_dynexecute) out, const PLpgSQL_stmt_dynexecute *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_dynexecute, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_dynexecute, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_dynexecute, PLpgSQL_expr, p__lpg_sql_expr, query, query, query);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_dynexecute, into, into, into);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_dynexecute, strict, strict, strict);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_dynexecute, target_dno, target_dno, target);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_dynexecute, PLpgSQL_expr, params, params, params);
}

static void
_outPLpgSQL_stmt_dynfors(OUT_TYPE(PLpgSQL_stmt_dynfors, PLpgSQL_stmt_dynfors) out, const PLpgSQL_stmt_dynfors *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_dynfors, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_dynfors, stmtid, stmtid, stmtid);
  WRITE_STRING_FIELD(PLpgSQL_stmt_dynfors, label, label, label);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_dynfors, var_dno, var_dno, var);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_dynfors, PLpgSQL_stmt, body, body, body);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_dynfors, PLpgSQL_expr, p__lpg_sql_expr, query, query, query);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_dynfors, PLpgSQL_expr, params, params, params);
}

static void
_outPLpgSQL_stmt_getdiag(OUT_TYPE(PLpgSQL_stmt_getdiag, PLpgSQL_stmt_getdiag) out, const PLpgSQL_stmt_getdiag *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_getdiag, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_getdiag, stmtid, stmtid, stmtid);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_getdiag, is_stacked, is_stacked, is_stacked);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_getdiag, PLpgSQL_diag_item, diag_items, diag_items, diag_items);
}

static void
_outPLpgSQL_stmt_open(OUT_TYPE(PLpgSQL_stmt_open, PLpgSQL_stmt_open) out, const PLpgSQL_stmt_open *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_open, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_open, stmtid, stmtid, stmtid);
  WRITE_INT_FIELD(PLpgSQL_stmt_open, curvar, curvar, curvar);
  WRITE_INT_FIELD(PLpgSQL_stmt_open, cursor_options, cursor_options, cursor_options);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_open, PLpgSQL_expr, p__lpg_sql_expr, argquery, argquery, argquery);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_open, PLpgSQL_expr, p__lpg_sql_expr, query, query, query);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_open, PLpgSQL_expr, p__lpg_sql_expr, dynquery, dynquery, dynquery);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_stmt_open, PLpgSQL_expr, params, params, params);
}

static void
_outPLpgSQL_stmt_fetch(OUT_TYPE(PLpgSQL_stmt_fetch, PLpgSQL_stmt_fetch) out, const PLpgSQL_stmt_fetch *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_fetch, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_fetch, stmtid, stmtid, stmtid);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_fetch, target_dno, target_dno, target);
  WRITE_INT_FIELD(PLpgSQL_stmt_fetch, curvar, curvar, curvar);
  WRITE_ENUM_FIELD(PLpgSQL_stmt_fetch, FetchDirection, direction, direction, direction);
  WRITE_LONG_FIELD(PLpgSQL_stmt_fetch, how_many, how_many, how_many);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_fetch, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_fetch, is_move, is_move, is_move);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_fetch, returns_multiple_rows, returns_multiple_rows, returns_multiple_rows);
}

static void
_outPLpgSQL_stmt_close(OUT_TYPE(PLpgSQL_stmt_close, PLpgSQL_stmt_close) out, const PLpgSQL_stmt_close *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_close, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_close, stmtid, stmtid, stmtid);
  WRITE_INT_FIELD(PLpgSQL_stmt_close, curvar, curvar, curvar);
}

static void
_outPLpgSQL_stmt_perform(OUT_TYPE(PLpgSQL_stmt_perform, PLpgSQL_stmt_perform) out, const PLpgSQL_stmt_perform *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_perform, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_perform, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_perform, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
}

static void
_outPLpgSQL_stmt_call(OUT_TYPE(PLpgSQL_stmt_call, PLpgSQL_stmt_call) out, const PLpgSQL_stmt_call *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_call, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_call, stmtid, stmtid, stmtid);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_stmt_call, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_call, is_call, is_call, is_call);
  WRITE_PLPGSQL_DATUM_REF_FIELD(PLpgSQL_stmt_call, target_dno, target_dno, target);
}

static void
_outPLpgSQL_stmt_commit(OUT_TYPE(PLpgSQL_stmt_commit, PLpgSQL_stmt_commit) out, const PLpgSQL_stmt_commit *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_commit, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_commit, stmtid, stmtid, stmtid);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_commit, chain, chain, chain);
}

static void
_outPLpgSQL_stmt_rollback(OUT_TYPE(PLpgSQL_stmt_rollback, PLpgSQL_stmt_rollback) out, const PLpgSQL_stmt_rollback *node)
{
  WRITE_INT_FIELD(PLpgSQL_stmt_rollback, lineno, lineno, lineno);
  WRITE_UINT_FIELD(PLpgSQL_stmt_rollback, stmtid, stmtid, stmtid);
  WRITE_BOOL_FIELD(PLpgSQL_stmt_rollback, chain, chain, chain);
}

static void
_outPLpgSQL_exception(OUT_TYPE(PLpgSQL_exception, PLpgSQL_exception) out, const PLpgSQL_exception *node)
{
  WRITE_INT_FIELD(PLpgSQL_exception, lineno, lineno, lineno);
  WRITE_PLPGSQL_LINKED_LIST_FIELD(PLpgSQL_exception, PLpgSQL_condition, conditions, conditions, conditions, next);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_exception, PLpgSQL_stmt, action, action, action);
}

static void
_outPLpgSQL_if_elsif(OUT_TYPE(PLpgSQL_if_elsif, PLpgSQL_if_elsif) out, const PLpgSQL_if_elsif *node)
{
  WRITE_INT_FIELD(PLpgSQL_if_elsif, lineno, lineno, lineno);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_if_elsif, PLpgSQL_expr, p__lpg_sql_expr, cond, cond, cond);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_if_elsif, PLpgSQL_stmt, stmts, stmts, stmts);
}

static void
_outPLpgSQL_case_when(OUT_TYPE(PLpgSQL_case_when, PLpgSQL_case_when) out, const PLpgSQL_case_when *node)
{
  WRITE_INT_FIELD(PLpgSQL_case_when, lineno, lineno, lineno);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_case_when, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
  WRITE_PLPGSQL_LIST_FIELD(PLpgSQL_case_when, PLpgSQL_stmt, stmts, stmts, stmts);
}

static void
_outPLpgSQL_raise_option(OUT_TYPE(PLpgSQL_raise_option, PLpgSQL_raise_option) out, const PLpgSQL_raise_option *node)
{
  WRITE_ENUM_FIELD(PLpgSQL_raise_option, PLpgSQL_raise_option_type, opt_type, opt_type, opt_type);
  WRITE_SPECIFIC_NODE_PTR_FIELD(PLpgSQL_raise_option, PLpgSQL_expr, p__lpg_sql_expr, expr, expr, expr);
}

static void
_outPLpgSQL_diag_item(OUT_TYPE(PLpgSQL_diag_item, PLpgSQL_diag_item) out, const PLpgSQL_diag_item *node)
{
  WRITE_ENUM_FIELD(PLpgSQL_diag_item, PLpgSQL_getdiag_kind, kind, kind, kind);
  WRITE_INT_FIELD(PLpgSQL_diag_item, target, target, target);
}

static void
_outPLpgSQL_condition(OUT_TYPE(PLpgSQL_condition, PLpgSQL_condition) out, const PLpgSQL_condition *node)
{
  WRITE_INT_FIELD(PLpgSQL_condition, sqlerrstate, sqlerrstate, sqlerrstate);
  WRITE_STRING_FIELD(PLpgSQL_condition, condname, condname, condname);
}

