// This file is autogenerated by ./scripts/generate_plpgsql_protobuf.rb

// Forward declarations for dispatchers
static PLpgSQL_stmt * _readPLpgSQL_stmt(const PgQuery__PLpgSQLStmt *msg);
static PLpgSQL_datum * _readPLpgSQL_datum(const PgQuery__PLpgSQLDatum *msg);


static PLpgSQL_type * _readPLpgSQL_type(const PgQuery__PLpgSQLType *msg);
static PLpgSQL_expr * _readPLpgSQL_expr(const PgQuery__PLpgSQLExpr *msg);
static PLpgSQL_var * _readPLpgSQL_var(const PgQuery__PLpgSQLVar *msg);
static PLpgSQL_row * _readPLpgSQL_row(const PgQuery__PLpgSQLRow *msg);
static PLpgSQL_rec * _readPLpgSQL_rec(const PgQuery__PLpgSQLRec *msg);
static PLpgSQL_recfield * _readPLpgSQL_recfield(const PgQuery__PLpgSQLRecfield *msg);
static PLpgSQL_condition * _readPLpgSQL_condition(const PgQuery__PLpgSQLCondition *msg);
static PLpgSQL_exception_block * _readPLpgSQL_exception_block(const PgQuery__PLpgSQLExceptionBlock *msg);
static PLpgSQL_exception * _readPLpgSQL_exception(const PgQuery__PLpgSQLException *msg);
static PLpgSQL_stmt_block * _readPLpgSQL_stmt_block(const PgQuery__PLpgSQLStmtBlock *msg);
static PLpgSQL_stmt_assign * _readPLpgSQL_stmt_assign(const PgQuery__PLpgSQLStmtAssign *msg);
static PLpgSQL_stmt_perform * _readPLpgSQL_stmt_perform(const PgQuery__PLpgSQLStmtPerform *msg);
static PLpgSQL_stmt_call * _readPLpgSQL_stmt_call(const PgQuery__PLpgSQLStmtCall *msg);
static PLpgSQL_stmt_commit * _readPLpgSQL_stmt_commit(const PgQuery__PLpgSQLStmtCommit *msg);
static PLpgSQL_stmt_rollback * _readPLpgSQL_stmt_rollback(const PgQuery__PLpgSQLStmtRollback *msg);
static PLpgSQL_diag_item * _readPLpgSQL_diag_item(const PgQuery__PLpgSQLDiagItem *msg);
static PLpgSQL_stmt_getdiag * _readPLpgSQL_stmt_getdiag(const PgQuery__PLpgSQLStmtGetdiag *msg);
static PLpgSQL_stmt_if * _readPLpgSQL_stmt_if(const PgQuery__PLpgSQLStmtIf *msg);
static PLpgSQL_if_elsif * _readPLpgSQL_if_elsif(const PgQuery__PLpgSQLIfElsif *msg);
static PLpgSQL_stmt_case * _readPLpgSQL_stmt_case(const PgQuery__PLpgSQLStmtCase *msg);
static PLpgSQL_case_when * _readPLpgSQL_case_when(const PgQuery__PLpgSQLCaseWhen *msg);
static PLpgSQL_stmt_loop * _readPLpgSQL_stmt_loop(const PgQuery__PLpgSQLStmtLoop *msg);
static PLpgSQL_stmt_while * _readPLpgSQL_stmt_while(const PgQuery__PLpgSQLStmtWhile *msg);
static PLpgSQL_stmt_fori * _readPLpgSQL_stmt_fori(const PgQuery__PLpgSQLStmtFori *msg);
static PLpgSQL_stmt_fors * _readPLpgSQL_stmt_fors(const PgQuery__PLpgSQLStmtFors *msg);
static PLpgSQL_stmt_forc * _readPLpgSQL_stmt_forc(const PgQuery__PLpgSQLStmtForc *msg);
static PLpgSQL_stmt_dynfors * _readPLpgSQL_stmt_dynfors(const PgQuery__PLpgSQLStmtDynfors *msg);
static PLpgSQL_stmt_foreach_a * _readPLpgSQL_stmt_foreach_a(const PgQuery__PLpgSQLStmtForeachA *msg);
static PLpgSQL_stmt_open * _readPLpgSQL_stmt_open(const PgQuery__PLpgSQLStmtOpen *msg);
static PLpgSQL_stmt_fetch * _readPLpgSQL_stmt_fetch(const PgQuery__PLpgSQLStmtFetch *msg);
static PLpgSQL_stmt_close * _readPLpgSQL_stmt_close(const PgQuery__PLpgSQLStmtClose *msg);
static PLpgSQL_stmt_exit * _readPLpgSQL_stmt_exit(const PgQuery__PLpgSQLStmtExit *msg);
static PLpgSQL_stmt_return * _readPLpgSQL_stmt_return(const PgQuery__PLpgSQLStmtReturn *msg);
static PLpgSQL_stmt_return_next * _readPLpgSQL_stmt_return_next(const PgQuery__PLpgSQLStmtReturnNext *msg);
static PLpgSQL_stmt_return_query * _readPLpgSQL_stmt_return_query(const PgQuery__PLpgSQLStmtReturnQuery *msg);
static PLpgSQL_stmt_raise * _readPLpgSQL_stmt_raise(const PgQuery__PLpgSQLStmtRaise *msg);
static PLpgSQL_raise_option * _readPLpgSQL_raise_option(const PgQuery__PLpgSQLRaiseOption *msg);
static PLpgSQL_stmt_assert * _readPLpgSQL_stmt_assert(const PgQuery__PLpgSQLStmtAssert *msg);
static PLpgSQL_stmt_execsql * _readPLpgSQL_stmt_execsql(const PgQuery__PLpgSQLStmtExecsql *msg);
static PLpgSQL_stmt_dynexecute * _readPLpgSQL_stmt_dynexecute(const PgQuery__PLpgSQLStmtDynexecute *msg);
static PLpgSQL_function * _readPLpgSQL_function(const PgQuery__PLpgSQLFunction *msg);


static PLpgSQL_stmt *
_readPLpgSQL_stmt(const PgQuery__PLpgSQLStmt *msg)
{
  switch (msg->stmt_case) {
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_BLOCK:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_block(msg->stmt_block);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_ASSIGN:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_assign(msg->stmt_assign);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_IF:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_if(msg->stmt_if);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_CASE_:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_case(msg->stmt_case_);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_LOOP:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_loop(msg->stmt_loop);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_WHILE:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_while(msg->stmt_while);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FORI:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_fori(msg->stmt_fori);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FORS:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_fors(msg->stmt_fors);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FORC:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_forc(msg->stmt_forc);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FOREACH_A:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_foreach_a(msg->stmt_foreach_a);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_EXIT:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_exit(msg->stmt_exit);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RETURN:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_return(msg->stmt_return);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RETURN_NEXT:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_return_next(msg->stmt_return_next);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RETURN_QUERY:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_return_query(msg->stmt_return_query);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_RAISE:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_raise(msg->stmt_raise);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_ASSERT:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_assert(msg->stmt_assert);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_EXECSQL:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_execsql(msg->stmt_execsql);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_DYNEXECUTE:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_dynexecute(msg->stmt_dynexecute);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_DYNFORS:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_dynfors(msg->stmt_dynfors);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_GETDIAG:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_getdiag(msg->stmt_getdiag);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_OPEN:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_open(msg->stmt_open);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_FETCH:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_fetch(msg->stmt_fetch);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_CLOSE:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_close(msg->stmt_close);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_PERFORM:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_perform(msg->stmt_perform);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_CALL:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_call(msg->stmt_call);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_COMMIT:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_commit(msg->stmt_commit);
    case PG_QUERY__PLPG_SQL_STMT__STMT_STMT_ROLLBACK:
      return (PLpgSQL_stmt *) _readPLpgSQL_stmt_rollback(msg->stmt_rollback);
    default:
      return NULL;
  }
}



static PLpgSQL_datum *
_readPLpgSQL_datum(const PgQuery__PLpgSQLDatum *msg)
{
  switch (msg->datum_case) {
    case PG_QUERY__PLPG_SQL_DATUM__DATUM_VAR:
      return (PLpgSQL_datum *) _readPLpgSQL_var(msg->var);
    case PG_QUERY__PLPG_SQL_DATUM__DATUM_ROW:
      return (PLpgSQL_datum *) _readPLpgSQL_row(msg->row);
    case PG_QUERY__PLPG_SQL_DATUM__DATUM_REC:
      return (PLpgSQL_datum *) _readPLpgSQL_rec(msg->rec);
    case PG_QUERY__PLPG_SQL_DATUM__DATUM_RECFIELD:
      return (PLpgSQL_datum *) _readPLpgSQL_recfield(msg->recfield);
    default:
      return NULL;
  }
}



static PLpgSQL_type *
_readPLpgSQL_type(const PgQuery__PLpgSQLType *msg)
{
  PLpgSQL_type *node = palloc0(sizeof(PLpgSQL_type));
  READ_STRING_FIELD(typname, typname);
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_type_type, ttype, ttype);
  return node;
}

static PLpgSQL_expr *
_readPLpgSQL_expr(const PgQuery__PLpgSQLExpr *msg)
{
  PLpgSQL_expr *node = palloc0(sizeof(PLpgSQL_expr));
  READ_STRING_FIELD(query, query);
  READ_INT_FIELD(parse_mode, parseMode);
  return node;
}

static PLpgSQL_var *
_readPLpgSQL_var(const PgQuery__PLpgSQLVar *msg)
{
  PLpgSQL_var *node = palloc0(sizeof(PLpgSQL_var));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  READ_INT_FIELD(dno, dno);
  READ_STRING_FIELD(refname, refname);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(isconst, isconst);
  READ_BOOL_FIELD(notnull, notnull);
  READ_PLPGSQL_EXPR_FIELD(default_val, default_val);
  READ_PLPGSQL_TYPE_FIELD(datatype, datatype);
  READ_PLPGSQL_EXPR_FIELD(cursor_explicit_expr, cursor_explicit_expr);
  READ_INT_FIELD(cursor_explicit_argrow, cursor_explicit_argrow);
  READ_INT_FIELD(cursor_options, cursor_options);
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_promise_type, promise, promise);
  return node;
}

static PLpgSQL_row *
_readPLpgSQL_row(const PgQuery__PLpgSQLRow *msg)
{
  PLpgSQL_row *node = palloc0(sizeof(PLpgSQL_row));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  READ_INT_FIELD(dno, dno);
  READ_STRING_FIELD(refname, refname);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(isconst, isconst);
  READ_BOOL_FIELD(notnull, notnull);
  READ_PLPGSQL_EXPR_FIELD(default_val, default_val);
  READ_INT_FIELD(nfields, nfields);
  return node;
}

static PLpgSQL_rec *
_readPLpgSQL_rec(const PgQuery__PLpgSQLRec *msg)
{
  PLpgSQL_rec *node = palloc0(sizeof(PLpgSQL_rec));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  READ_INT_FIELD(dno, dno);
  READ_STRING_FIELD(refname, refname);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(isconst, isconst);
  READ_BOOL_FIELD(notnull, notnull);
  READ_PLPGSQL_EXPR_FIELD(default_val, default_val);
  READ_PLPGSQL_TYPE_FIELD(datatype, datatype);
  READ_INT_FIELD(firstfield, firstfield);
  return node;
}

static PLpgSQL_recfield *
_readPLpgSQL_recfield(const PgQuery__PLpgSQLRecfield *msg)
{
  PLpgSQL_recfield *node = palloc0(sizeof(PLpgSQL_recfield));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_datum_type, dtype, dtype);
  READ_INT_FIELD(dno, dno);
  READ_STRING_FIELD(fieldname, fieldname);
  READ_INT_FIELD(recparentno, recparentno);
  READ_INT_FIELD(nextfield, nextfield);
  return node;
}

static PLpgSQL_condition *
_readPLpgSQL_condition(const PgQuery__PLpgSQLCondition *msg)
{
  PLpgSQL_condition *node = palloc0(sizeof(PLpgSQL_condition));
  READ_INT_FIELD(sqlerrstate, sqlerrstate);
  READ_STRING_FIELD(condname, condname);
  return node;
}

static PLpgSQL_exception_block *
_readPLpgSQL_exception_block(const PgQuery__PLpgSQLExceptionBlock *msg)
{
  PLpgSQL_exception_block *node = palloc0(sizeof(PLpgSQL_exception_block));
  READ_INT_FIELD(sqlstate_varno, sqlstate_varno);
  READ_INT_FIELD(sqlerrm_varno, sqlerrm_varno);
  READ_PLPGSQL_EXCEPTION_LIST_FIELD(exc_list, exc_list);
  return node;
}

static PLpgSQL_exception *
_readPLpgSQL_exception(const PgQuery__PLpgSQLException *msg)
{
  PLpgSQL_exception *node = palloc0(sizeof(PLpgSQL_exception));
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_CONDITION_FIELD(conditions, conditions);
  READ_PLPGSQL_STMT_LIST_FIELD(action, action);
  return node;
}

static PLpgSQL_stmt_block *
_readPLpgSQL_stmt_block(const PgQuery__PLpgSQLStmtBlock *msg)
{
  PLpgSQL_stmt_block *node = palloc0(sizeof(PLpgSQL_stmt_block));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  READ_INT_FIELD(n_initvars, n_initvars);
  READ_PLPGSQL_EXCEPTION_BLOCK_FIELD(exceptions, exceptions);
  return node;
}

static PLpgSQL_stmt_assign *
_readPLpgSQL_stmt_assign(const PgQuery__PLpgSQLStmtAssign *msg)
{
  PLpgSQL_stmt_assign *node = palloc0(sizeof(PLpgSQL_stmt_assign));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_INT_FIELD(varno, varno);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  return node;
}

static PLpgSQL_stmt_perform *
_readPLpgSQL_stmt_perform(const PgQuery__PLpgSQLStmtPerform *msg)
{
  PLpgSQL_stmt_perform *node = palloc0(sizeof(PLpgSQL_stmt_perform));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  return node;
}

static PLpgSQL_stmt_call *
_readPLpgSQL_stmt_call(const PgQuery__PLpgSQLStmtCall *msg)
{
  PLpgSQL_stmt_call *node = palloc0(sizeof(PLpgSQL_stmt_call));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  READ_BOOL_FIELD(is_call, is_call);
  READ_PLPGSQL_DATUM_FIELD(target, target);
  return node;
}

static PLpgSQL_stmt_commit *
_readPLpgSQL_stmt_commit(const PgQuery__PLpgSQLStmtCommit *msg)
{
  PLpgSQL_stmt_commit *node = palloc0(sizeof(PLpgSQL_stmt_commit));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(chain, chain);
  return node;
}

static PLpgSQL_stmt_rollback *
_readPLpgSQL_stmt_rollback(const PgQuery__PLpgSQLStmtRollback *msg)
{
  PLpgSQL_stmt_rollback *node = palloc0(sizeof(PLpgSQL_stmt_rollback));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(chain, chain);
  return node;
}

static PLpgSQL_diag_item *
_readPLpgSQL_diag_item(const PgQuery__PLpgSQLDiagItem *msg)
{
  PLpgSQL_diag_item *node = palloc0(sizeof(PLpgSQL_diag_item));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_getdiag_kind, kind, kind);
  READ_INT_FIELD(target, target);
  return node;
}

static PLpgSQL_stmt_getdiag *
_readPLpgSQL_stmt_getdiag(const PgQuery__PLpgSQLStmtGetdiag *msg)
{
  PLpgSQL_stmt_getdiag *node = palloc0(sizeof(PLpgSQL_stmt_getdiag));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(is_stacked, is_stacked);
  READ_PLPGSQL_DIAG_ITEM_LIST_FIELD(diag_items, diag_items);
  return node;
}

static PLpgSQL_stmt_if *
_readPLpgSQL_stmt_if(const PgQuery__PLpgSQLStmtIf *msg)
{
  PLpgSQL_stmt_if *node = palloc0(sizeof(PLpgSQL_stmt_if));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(cond, cond);
  READ_PLPGSQL_STMT_LIST_FIELD(then_body, then_body);
  READ_PLPGSQL_IF_ELSIF_LIST_FIELD(elsif_list, elsif_list);
  READ_PLPGSQL_STMT_LIST_FIELD(else_body, else_body);
  return node;
}

static PLpgSQL_if_elsif *
_readPLpgSQL_if_elsif(const PgQuery__PLpgSQLIfElsif *msg)
{
  PLpgSQL_if_elsif *node = palloc0(sizeof(PLpgSQL_if_elsif));
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(cond, cond);
  READ_PLPGSQL_STMT_LIST_FIELD(stmts, stmts);
  return node;
}

static PLpgSQL_stmt_case *
_readPLpgSQL_stmt_case(const PgQuery__PLpgSQLStmtCase *msg)
{
  PLpgSQL_stmt_case *node = palloc0(sizeof(PLpgSQL_stmt_case));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(t_expr, t_expr);
  READ_INT_FIELD(t_varno, t_varno);
  READ_PLPGSQL_CASE_WHEN_LIST_FIELD(case_when_list, case_when_list);
  READ_BOOL_FIELD(have_else, have_else);
  READ_PLPGSQL_STMT_LIST_FIELD(else_stmts, else_stmts);
  return node;
}

static PLpgSQL_case_when *
_readPLpgSQL_case_when(const PgQuery__PLpgSQLCaseWhen *msg)
{
  PLpgSQL_case_when *node = palloc0(sizeof(PLpgSQL_case_when));
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  READ_PLPGSQL_STMT_LIST_FIELD(stmts, stmts);
  return node;
}

static PLpgSQL_stmt_loop *
_readPLpgSQL_stmt_loop(const PgQuery__PLpgSQLStmtLoop *msg)
{
  PLpgSQL_stmt_loop *node = palloc0(sizeof(PLpgSQL_stmt_loop));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  return node;
}

static PLpgSQL_stmt_while *
_readPLpgSQL_stmt_while(const PgQuery__PLpgSQLStmtWhile *msg)
{
  PLpgSQL_stmt_while *node = palloc0(sizeof(PLpgSQL_stmt_while));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_EXPR_FIELD(cond, cond);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  return node;
}

static PLpgSQL_stmt_fori *
_readPLpgSQL_stmt_fori(const PgQuery__PLpgSQLStmtFori *msg)
{
  PLpgSQL_stmt_fori *node = palloc0(sizeof(PLpgSQL_stmt_fori));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_VAR_FIELD(var, var);
  READ_PLPGSQL_EXPR_FIELD(lower, lower);
  READ_PLPGSQL_EXPR_FIELD(upper, upper);
  READ_PLPGSQL_EXPR_FIELD(step, step);
  READ_INT_FIELD(reverse, reverse);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  return node;
}

static PLpgSQL_stmt_fors *
_readPLpgSQL_stmt_fors(const PgQuery__PLpgSQLStmtFors *msg)
{
  PLpgSQL_stmt_fors *node = palloc0(sizeof(PLpgSQL_stmt_fors));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_DATUM_FIELD(var, var);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  READ_PLPGSQL_EXPR_FIELD(query, query);
  return node;
}

static PLpgSQL_stmt_forc *
_readPLpgSQL_stmt_forc(const PgQuery__PLpgSQLStmtForc *msg)
{
  PLpgSQL_stmt_forc *node = palloc0(sizeof(PLpgSQL_stmt_forc));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_DATUM_FIELD(var, var);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  READ_INT_FIELD(curvar, curvar);
  READ_PLPGSQL_EXPR_FIELD(argquery, argquery);
  return node;
}

static PLpgSQL_stmt_dynfors *
_readPLpgSQL_stmt_dynfors(const PgQuery__PLpgSQLStmtDynfors *msg)
{
  PLpgSQL_stmt_dynfors *node = palloc0(sizeof(PLpgSQL_stmt_dynfors));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_DATUM_FIELD(var, var);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  READ_PLPGSQL_EXPR_FIELD(query, query);
  READ_PLPGSQL_EXPR_LIST_FIELD(params, params);
  return node;
}

static PLpgSQL_stmt_foreach_a *
_readPLpgSQL_stmt_foreach_a(const PgQuery__PLpgSQLStmtForeachA *msg)
{
  PLpgSQL_stmt_foreach_a *node = palloc0(sizeof(PLpgSQL_stmt_foreach_a));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_STRING_FIELD(label, label);
  READ_INT_FIELD(varno, varno);
  READ_INT_FIELD(slice, slice);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  READ_PLPGSQL_STMT_LIST_FIELD(body, body);
  return node;
}

static PLpgSQL_stmt_open *
_readPLpgSQL_stmt_open(const PgQuery__PLpgSQLStmtOpen *msg)
{
  PLpgSQL_stmt_open *node = palloc0(sizeof(PLpgSQL_stmt_open));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_INT_FIELD(curvar, curvar);
  READ_INT_FIELD(cursor_options, cursor_options);
  READ_PLPGSQL_EXPR_FIELD(argquery, argquery);
  READ_PLPGSQL_EXPR_FIELD(query, query);
  READ_PLPGSQL_EXPR_FIELD(dynquery, dynquery);
  READ_PLPGSQL_EXPR_LIST_FIELD(params, params);
  return node;
}

static PLpgSQL_stmt_fetch *
_readPLpgSQL_stmt_fetch(const PgQuery__PLpgSQLStmtFetch *msg)
{
  PLpgSQL_stmt_fetch *node = palloc0(sizeof(PLpgSQL_stmt_fetch));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_DATUM_FIELD(target, target);
  READ_INT_FIELD(curvar, curvar);
  READ_INT_FIELD(direction, direction);
  READ_LONG_FIELD(how_many, how_many);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  READ_BOOL_FIELD(is_move, is_move);
  READ_BOOL_FIELD(returns_multiple_rows, returns_multiple_rows);
  return node;
}

static PLpgSQL_stmt_close *
_readPLpgSQL_stmt_close(const PgQuery__PLpgSQLStmtClose *msg)
{
  PLpgSQL_stmt_close *node = palloc0(sizeof(PLpgSQL_stmt_close));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_INT_FIELD(curvar, curvar);
  return node;
}

static PLpgSQL_stmt_exit *
_readPLpgSQL_stmt_exit(const PgQuery__PLpgSQLStmtExit *msg)
{
  PLpgSQL_stmt_exit *node = palloc0(sizeof(PLpgSQL_stmt_exit));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_BOOL_FIELD(is_exit, is_exit);
  READ_STRING_FIELD(label, label);
  READ_PLPGSQL_EXPR_FIELD(cond, cond);
  return node;
}

static PLpgSQL_stmt_return *
_readPLpgSQL_stmt_return(const PgQuery__PLpgSQLStmtReturn *msg)
{
  PLpgSQL_stmt_return *node = palloc0(sizeof(PLpgSQL_stmt_return));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  READ_INT_FIELD(retvarno, retvarno);
  return node;
}

static PLpgSQL_stmt_return_next *
_readPLpgSQL_stmt_return_next(const PgQuery__PLpgSQLStmtReturnNext *msg)
{
  PLpgSQL_stmt_return_next *node = palloc0(sizeof(PLpgSQL_stmt_return_next));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  READ_INT_FIELD(retvarno, retvarno);
  return node;
}

static PLpgSQL_stmt_return_query *
_readPLpgSQL_stmt_return_query(const PgQuery__PLpgSQLStmtReturnQuery *msg)
{
  PLpgSQL_stmt_return_query *node = palloc0(sizeof(PLpgSQL_stmt_return_query));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(query, query);
  READ_PLPGSQL_EXPR_FIELD(dynquery, dynquery);
  READ_PLPGSQL_EXPR_LIST_FIELD(params, params);
  return node;
}

static PLpgSQL_stmt_raise *
_readPLpgSQL_stmt_raise(const PgQuery__PLpgSQLStmtRaise *msg)
{
  PLpgSQL_stmt_raise *node = palloc0(sizeof(PLpgSQL_stmt_raise));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_INT_FIELD(elog_level, elog_level);
  READ_STRING_FIELD(condname, condname);
  READ_STRING_FIELD(message, message);
  READ_PLPGSQL_EXPR_LIST_FIELD(params, params);
  READ_PLPGSQL_RAISE_OPTION_LIST_FIELD(options, options);
  return node;
}

static PLpgSQL_raise_option *
_readPLpgSQL_raise_option(const PgQuery__PLpgSQLRaiseOption *msg)
{
  PLpgSQL_raise_option *node = palloc0(sizeof(PLpgSQL_raise_option));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_raise_option_type, opt_type, opt_type);
  READ_PLPGSQL_EXPR_FIELD(expr, expr);
  return node;
}

static PLpgSQL_stmt_assert *
_readPLpgSQL_stmt_assert(const PgQuery__PLpgSQLStmtAssert *msg)
{
  PLpgSQL_stmt_assert *node = palloc0(sizeof(PLpgSQL_stmt_assert));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(cond, cond);
  READ_PLPGSQL_EXPR_FIELD(message, message);
  return node;
}

static PLpgSQL_stmt_execsql *
_readPLpgSQL_stmt_execsql(const PgQuery__PLpgSQLStmtExecsql *msg)
{
  PLpgSQL_stmt_execsql *node = palloc0(sizeof(PLpgSQL_stmt_execsql));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(sqlstmt, sqlstmt);
  READ_BOOL_FIELD(mod_stmt, mod_stmt);
  READ_BOOL_FIELD(mod_stmt_set, mod_stmt_set);
  READ_BOOL_FIELD(into, into);
  READ_BOOL_FIELD(strict, strict);
  READ_PLPGSQL_DATUM_FIELD(target, target);
  return node;
}

static PLpgSQL_stmt_dynexecute *
_readPLpgSQL_stmt_dynexecute(const PgQuery__PLpgSQLStmtDynexecute *msg)
{
  PLpgSQL_stmt_dynexecute *node = palloc0(sizeof(PLpgSQL_stmt_dynexecute));
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_stmt_type, cmd_type, cmd_type);
  READ_INT_FIELD(lineno, lineno);
  READ_PLPGSQL_EXPR_FIELD(query, query);
  READ_BOOL_FIELD(into, into);
  READ_BOOL_FIELD(strict, strict);
  READ_PLPGSQL_DATUM_FIELD(target, target);
  READ_PLPGSQL_EXPR_LIST_FIELD(params, params);
  return node;
}

static PLpgSQL_function *
_readPLpgSQL_function(const PgQuery__PLpgSQLFunction *msg)
{
  PLpgSQL_function *node = palloc0(sizeof(PLpgSQL_function));
  READ_STRING_FIELD(fn_signature, fn_signature);
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_trigtype, fn_is_trigger, fn_is_trigger);
  READ_INT_FIELD(out_param_varno, out_param_varno);
  READ_INT_FIELD(found_varno, found_varno);
  READ_INT_FIELD(new_varno, new_varno);
  READ_INT_FIELD(old_varno, old_varno);
  READ_PLPGSQL_ENUM_FIELD(PLpgSQL_resolve_option, resolve_option, resolve_option);
  READ_BOOL_FIELD(print_strict_params, print_strict_params);
  READ_INT_FIELD(extra_warnings, extra_warnings);
  READ_INT_FIELD(extra_errors, extra_errors);
  READ_INT_FIELD(ndatums, ndatums);
  READ_PLPGSQL_STMT_BLOCK_FIELD(action, action);
  return node;
}


